#ifndef _boat1_
#define _boat1_

#include "RenderData.h"

//This file was auto generated by Model Converter v0.5

RenderData* Getboat1()
{ 
	RenderData* model = new RenderData();
	model->m_numVertices = 150;
	model->m_numIndices = 150;
	model->m_numColorData = 0;
	model->m_numTexCoords = 150;

	model->m_vertices = new Vector3[model->m_numVertices];
	model->m_indices = new uint16[model->m_numIndices];
	model->m_texCoords = new TexCoord2[model->m_numTexCoords];

	model->m_vertices[0].x = 0;
	model->m_vertices[0].y = -615488;
	model->m_vertices[0].z = 47580;

	model->m_vertices[1].x = 0;
	model->m_vertices[1].y = -43126;
	model->m_vertices[1].z = -24431;

	model->m_vertices[2].x = 141557;
	model->m_vertices[2].y = -391358;
	model->m_vertices[2].z = 47580;

	model->m_vertices[3].x = 99405;
	model->m_vertices[3].y = -72336;
	model->m_vertices[3].z = -10770;

	model->m_vertices[4].x = 177984;
	model->m_vertices[4].y = -231737;
	model->m_vertices[4].z = 72637;

	model->m_vertices[5].x = 141557;
	model->m_vertices[5].y = -391358;
	model->m_vertices[5].z = 47580;

	model->m_vertices[6].x = 141557;
	model->m_vertices[6].y = -391358;
	model->m_vertices[6].z = 47580;

	model->m_vertices[7].x = 0;
	model->m_vertices[7].y = -334796;
	model->m_vertices[7].z = 65455;

	model->m_vertices[8].x = 0;
	model->m_vertices[8].y = -615488;
	model->m_vertices[8].z = 47580;

	model->m_vertices[9].x = 0;
	model->m_vertices[9].y = -43126;
	model->m_vertices[9].z = -24431;

	model->m_vertices[10].x = 0;
	model->m_vertices[10].y = -615488;
	model->m_vertices[10].z = 47580;

	model->m_vertices[11].x = -141557;
	model->m_vertices[11].y = -391358;
	model->m_vertices[11].z = 47580;

	model->m_vertices[12].x = -99405;
	model->m_vertices[12].y = -72336;
	model->m_vertices[12].z = -10770;

	model->m_vertices[13].x = 0;
	model->m_vertices[13].y = -43126;
	model->m_vertices[13].z = -24431;

	model->m_vertices[14].x = -141557;
	model->m_vertices[14].y = -391358;
	model->m_vertices[14].z = 47580;

	model->m_vertices[15].x = -99405;
	model->m_vertices[15].y = -72336;
	model->m_vertices[15].z = -10770;

	model->m_vertices[16].x = -141557;
	model->m_vertices[16].y = -391358;
	model->m_vertices[16].z = 47580;

	model->m_vertices[17].x = -177984;
	model->m_vertices[17].y = -231737;
	model->m_vertices[17].z = 72637;

	model->m_vertices[18].x = 0;
	model->m_vertices[18].y = -615488;
	model->m_vertices[18].z = 47580;

	model->m_vertices[19].x = 0;
	model->m_vertices[19].y = -334796;
	model->m_vertices[19].z = 65455;

	model->m_vertices[20].x = -141557;
	model->m_vertices[20].y = -391358;
	model->m_vertices[20].z = 47580;

	model->m_vertices[21].x = 141557;
	model->m_vertices[21].y = -391358;
	model->m_vertices[21].z = 47580;

	model->m_vertices[22].x = 0;
	model->m_vertices[22].y = -43126;
	model->m_vertices[22].z = -24431;

	model->m_vertices[23].x = 99405;
	model->m_vertices[23].y = -72336;
	model->m_vertices[23].z = -10770;

	model->m_vertices[24].x = 177984;
	model->m_vertices[24].y = -231737;
	model->m_vertices[24].z = 72637;

	model->m_vertices[25].x = 88992;
	model->m_vertices[25].y = -254739;
	model->m_vertices[25].z = 69046;

	model->m_vertices[26].x = 141557;
	model->m_vertices[26].y = -391358;
	model->m_vertices[26].z = 47580;

	model->m_vertices[27].x = 0;
	model->m_vertices[27].y = -334796;
	model->m_vertices[27].z = 65455;

	model->m_vertices[28].x = -88992;
	model->m_vertices[28].y = -254739;
	model->m_vertices[28].z = 69046;

	model->m_vertices[29].x = -141557;
	model->m_vertices[29].y = -391358;
	model->m_vertices[29].z = 47580;

	model->m_vertices[30].x = 99405;
	model->m_vertices[30].y = -72336;
	model->m_vertices[30].z = -10770;

	model->m_vertices[31].x = 0;
	model->m_vertices[31].y = -43126;
	model->m_vertices[31].z = -24431;

	model->m_vertices[32].x = 84922;
	model->m_vertices[32].y = 263258;
	model->m_vertices[32].z = 40713;

	model->m_vertices[33].x = -177984;
	model->m_vertices[33].y = -231737;
	model->m_vertices[33].z = 72637;

	model->m_vertices[34].x = -135927;
	model->m_vertices[34].y = 113324;
	model->m_vertices[34].z = 56542;

	model->m_vertices[35].x = -99405;
	model->m_vertices[35].y = -72336;
	model->m_vertices[35].z = -10770;

	model->m_vertices[36].x = -84922;
	model->m_vertices[36].y = 263258;
	model->m_vertices[36].z = 40713;

	model->m_vertices[37].x = 0;
	model->m_vertices[37].y = -43126;
	model->m_vertices[37].z = -24431;

	model->m_vertices[38].x = -99405;
	model->m_vertices[38].y = -72336;
	model->m_vertices[38].z = -10770;

	model->m_vertices[39].x = 135927;
	model->m_vertices[39].y = 113324;
	model->m_vertices[39].z = 56542;

	model->m_vertices[40].x = 84922;
	model->m_vertices[40].y = 263258;
	model->m_vertices[40].z = 40713;

	model->m_vertices[41].x = 0;
	model->m_vertices[41].y = 10000;
	model->m_vertices[41].z = 118119;

	model->m_vertices[42].x = -135927;
	model->m_vertices[42].y = 113324;
	model->m_vertices[42].z = 56542;

	model->m_vertices[43].x = 0;
	model->m_vertices[43].y = 10000;
	model->m_vertices[43].z = 118119;

	model->m_vertices[44].x = -84922;
	model->m_vertices[44].y = 263258;
	model->m_vertices[44].z = 40713;

	model->m_vertices[45].x = 0;
	model->m_vertices[45].y = 263258;
	model->m_vertices[45].z = -33653;

	model->m_vertices[46].x = 0;
	model->m_vertices[46].y = -43126;
	model->m_vertices[46].z = -24431;

	model->m_vertices[47].x = -84922;
	model->m_vertices[47].y = 263258;
	model->m_vertices[47].z = 40713;

	model->m_vertices[48].x = -84922;
	model->m_vertices[48].y = 263258;
	model->m_vertices[48].z = 40713;

	model->m_vertices[49].x = 84922;
	model->m_vertices[49].y = 263258;
	model->m_vertices[49].z = 40713;

	model->m_vertices[50].x = 0;
	model->m_vertices[50].y = 263258;
	model->m_vertices[50].z = -33653;

	model->m_vertices[51].x = 0;
	model->m_vertices[51].y = -43126;
	model->m_vertices[51].z = -24431;

	model->m_vertices[52].x = 0;
	model->m_vertices[52].y = 263258;
	model->m_vertices[52].z = -33653;

	model->m_vertices[53].x = 84922;
	model->m_vertices[53].y = 263258;
	model->m_vertices[53].z = 40713;

	model->m_vertices[54].x = -84922;
	model->m_vertices[54].y = 263258;
	model->m_vertices[54].z = 40713;

	model->m_vertices[55].x = 0;
	model->m_vertices[55].y = 10000;
	model->m_vertices[55].z = 118119;

	model->m_vertices[56].x = 0;
	model->m_vertices[56].y = 263258;
	model->m_vertices[56].z = 117785;

	model->m_vertices[57].x = 0;
	model->m_vertices[57].y = 10000;
	model->m_vertices[57].z = 118119;

	model->m_vertices[58].x = 84922;
	model->m_vertices[58].y = 263258;
	model->m_vertices[58].z = 40713;

	model->m_vertices[59].x = 0;
	model->m_vertices[59].y = 263258;
	model->m_vertices[59].z = 117785;

	model->m_vertices[60].x = -84922;
	model->m_vertices[60].y = 263258;
	model->m_vertices[60].z = 40713;

	model->m_vertices[61].x = 0;
	model->m_vertices[61].y = 263258;
	model->m_vertices[61].z = 117785;

	model->m_vertices[62].x = 84922;
	model->m_vertices[62].y = 263258;
	model->m_vertices[62].z = 40713;

	model->m_vertices[63].x = -88992;
	model->m_vertices[63].y = -254739;
	model->m_vertices[63].z = 69046;

	model->m_vertices[64].x = -103943;
	model->m_vertices[64].y = -122369;
	model->m_vertices[64].z = 86625;

	model->m_vertices[65].x = -177984;
	model->m_vertices[65].y = -231737;
	model->m_vertices[65].z = 72637;

	model->m_vertices[66].x = 135927;
	model->m_vertices[66].y = 113324;
	model->m_vertices[66].z = 56542;

	model->m_vertices[67].x = 103943;
	model->m_vertices[67].y = -122369;
	model->m_vertices[67].z = 86625;

	model->m_vertices[68].x = 177984;
	model->m_vertices[68].y = -231737;
	model->m_vertices[68].z = 72637;

	model->m_vertices[69].x = 177984;
	model->m_vertices[69].y = -231737;
	model->m_vertices[69].z = 72637;

	model->m_vertices[70].x = 99405;
	model->m_vertices[70].y = -72336;
	model->m_vertices[70].z = -10770;

	model->m_vertices[71].x = 135927;
	model->m_vertices[71].y = 113324;
	model->m_vertices[71].z = 56542;

	model->m_vertices[72].x = 223957;
	model->m_vertices[72].y = 122597;
	model->m_vertices[72].z = 50175;

	model->m_vertices[73].x = 99405;
	model->m_vertices[73].y = -72336;
	model->m_vertices[73].z = -10770;

	model->m_vertices[74].x = 181899;
	model->m_vertices[74].y = 272531;
	model->m_vertices[74].z = 34081;

	model->m_vertices[75].x = 84922;
	model->m_vertices[75].y = 263258;
	model->m_vertices[75].z = 40713;

	model->m_vertices[76].x = 181899;
	model->m_vertices[76].y = 272531;
	model->m_vertices[76].z = 34081;

	model->m_vertices[77].x = 99405;
	model->m_vertices[77].y = -72336;
	model->m_vertices[77].z = -10770;

	model->m_vertices[78].x = 223957;
	model->m_vertices[78].y = 122597;
	model->m_vertices[78].z = 50175;

	model->m_vertices[79].x = 181899;
	model->m_vertices[79].y = 272531;
	model->m_vertices[79].z = 34081;

	model->m_vertices[80].x = 135927;
	model->m_vertices[80].y = 113324;
	model->m_vertices[80].z = 56542;

	model->m_vertices[81].x = -135927;
	model->m_vertices[81].y = 113324;
	model->m_vertices[81].z = 56542;

	model->m_vertices[82].x = -223957;
	model->m_vertices[82].y = 122597;
	model->m_vertices[82].z = 50175;

	model->m_vertices[83].x = -99405;
	model->m_vertices[83].y = -72336;
	model->m_vertices[83].z = -10770;

	model->m_vertices[84].x = -84922;
	model->m_vertices[84].y = 263258;
	model->m_vertices[84].z = 40713;

	model->m_vertices[85].x = -181899;
	model->m_vertices[85].y = 272531;
	model->m_vertices[85].z = 34081;

	model->m_vertices[86].x = -135927;
	model->m_vertices[86].y = 113324;
	model->m_vertices[86].z = 56542;

	model->m_vertices[87].x = -223957;
	model->m_vertices[87].y = 122597;
	model->m_vertices[87].z = 50175;

	model->m_vertices[88].x = -181899;
	model->m_vertices[88].y = 272531;
	model->m_vertices[88].z = 34081;

	model->m_vertices[89].x = -99405;
	model->m_vertices[89].y = -72336;
	model->m_vertices[89].z = -10770;

	model->m_vertices[90].x = 88992;
	model->m_vertices[90].y = -254739;
	model->m_vertices[90].z = 69046;

	model->m_vertices[91].x = 0;
	model->m_vertices[91].y = -261578;
	model->m_vertices[91].z = 99863;

	model->m_vertices[92].x = 0;
	model->m_vertices[92].y = -334796;
	model->m_vertices[92].z = 65455;

	model->m_vertices[93].x = 44496;
	model->m_vertices[93].y = -130135;
	model->m_vertices[93].z = 140616;

	model->m_vertices[94].x = 0;
	model->m_vertices[94].y = 10000;
	model->m_vertices[94].z = 118119;

	model->m_vertices[95].x = -44496;
	model->m_vertices[95].y = -130135;
	model->m_vertices[95].z = 140616;

	model->m_vertices[96].x = -88992;
	model->m_vertices[96].y = -254739;
	model->m_vertices[96].z = 69046;

	model->m_vertices[97].x = 0;
	model->m_vertices[97].y = -334796;
	model->m_vertices[97].z = 65455;

	model->m_vertices[98].x = 0;
	model->m_vertices[98].y = -261578;
	model->m_vertices[98].z = 99863;

	model->m_vertices[99].x = -44496;
	model->m_vertices[99].y = -130135;
	model->m_vertices[99].z = 140616;

	model->m_vertices[100].x = 0;
	model->m_vertices[100].y = -261578;
	model->m_vertices[100].z = 99863;

	model->m_vertices[101].x = 44496;
	model->m_vertices[101].y = -130135;
	model->m_vertices[101].z = 140616;

	model->m_vertices[102].x = 0;
	model->m_vertices[102].y = 10000;
	model->m_vertices[102].z = 118119;

	model->m_vertices[103].x = 44496;
	model->m_vertices[103].y = -130135;
	model->m_vertices[103].z = 140616;

	model->m_vertices[104].x = 135927;
	model->m_vertices[104].y = 113324;
	model->m_vertices[104].z = 56542;

	model->m_vertices[105].x = 103943;
	model->m_vertices[105].y = -122369;
	model->m_vertices[105].z = 86625;

	model->m_vertices[106].x = 135927;
	model->m_vertices[106].y = 113324;
	model->m_vertices[106].z = 56542;

	model->m_vertices[107].x = 44496;
	model->m_vertices[107].y = -130135;
	model->m_vertices[107].z = 140616;

	model->m_vertices[108].x = 0;
	model->m_vertices[108].y = 10000;
	model->m_vertices[108].z = 118119;

	model->m_vertices[109].x = -135927;
	model->m_vertices[109].y = 113324;
	model->m_vertices[109].z = 56542;

	model->m_vertices[110].x = -44496;
	model->m_vertices[110].y = -130135;
	model->m_vertices[110].z = 140616;

	model->m_vertices[111].x = -44496;
	model->m_vertices[111].y = -130135;
	model->m_vertices[111].z = 140616;

	model->m_vertices[112].x = -135927;
	model->m_vertices[112].y = 113324;
	model->m_vertices[112].z = 56542;

	model->m_vertices[113].x = -103943;
	model->m_vertices[113].y = -122369;
	model->m_vertices[113].z = 86625;

	model->m_vertices[114].x = 88992;
	model->m_vertices[114].y = -254739;
	model->m_vertices[114].z = 69046;

	model->m_vertices[115].x = 177984;
	model->m_vertices[115].y = -231737;
	model->m_vertices[115].z = 72637;

	model->m_vertices[116].x = 103943;
	model->m_vertices[116].y = -122369;
	model->m_vertices[116].z = 86625;

	model->m_vertices[117].x = -135927;
	model->m_vertices[117].y = 113324;
	model->m_vertices[117].z = 56542;

	model->m_vertices[118].x = -177984;
	model->m_vertices[118].y = -231737;
	model->m_vertices[118].z = 72637;

	model->m_vertices[119].x = -103943;
	model->m_vertices[119].y = -122369;
	model->m_vertices[119].z = 86625;

	model->m_vertices[120].x = -84922;
	model->m_vertices[120].y = 263258;
	model->m_vertices[120].z = 40713;

	model->m_vertices[121].x = -99405;
	model->m_vertices[121].y = -72336;
	model->m_vertices[121].z = -10770;

	model->m_vertices[122].x = -181899;
	model->m_vertices[122].y = 272531;
	model->m_vertices[122].z = 34081;

	model->m_vertices[123].x = 135927;
	model->m_vertices[123].y = 113324;
	model->m_vertices[123].z = 56542;

	model->m_vertices[124].x = 99405;
	model->m_vertices[124].y = -72336;
	model->m_vertices[124].z = -10770;

	model->m_vertices[125].x = 223957;
	model->m_vertices[125].y = 122597;
	model->m_vertices[125].z = 50175;

	model->m_vertices[126].x = -177984;
	model->m_vertices[126].y = -231737;
	model->m_vertices[126].z = 72637;

	model->m_vertices[127].x = -141557;
	model->m_vertices[127].y = -391358;
	model->m_vertices[127].z = 47580;

	model->m_vertices[128].x = -88992;
	model->m_vertices[128].y = -254739;
	model->m_vertices[128].z = 69046;

	model->m_vertices[129].x = 0;
	model->m_vertices[129].y = -334796;
	model->m_vertices[129].z = 65455;

	model->m_vertices[130].x = 141557;
	model->m_vertices[130].y = -391358;
	model->m_vertices[130].z = 47580;

	model->m_vertices[131].x = 88992;
	model->m_vertices[131].y = -254739;
	model->m_vertices[131].z = 69046;

	model->m_vertices[132].x = 84922;
	model->m_vertices[132].y = 263258;
	model->m_vertices[132].z = 40713;

	model->m_vertices[133].x = 135927;
	model->m_vertices[133].y = 113324;
	model->m_vertices[133].z = 56542;

	model->m_vertices[134].x = 181899;
	model->m_vertices[134].y = 272531;
	model->m_vertices[134].z = 34081;

	model->m_vertices[135].x = -223957;
	model->m_vertices[135].y = 122597;
	model->m_vertices[135].z = 50175;

	model->m_vertices[136].x = -135927;
	model->m_vertices[136].y = 113324;
	model->m_vertices[136].z = 56542;

	model->m_vertices[137].x = -181899;
	model->m_vertices[137].y = 272531;
	model->m_vertices[137].z = 34081;

	model->m_vertices[138].x = 0;
	model->m_vertices[138].y = -261578;
	model->m_vertices[138].z = 99863;

	model->m_vertices[139].x = -44496;
	model->m_vertices[139].y = -130135;
	model->m_vertices[139].z = 140616;

	model->m_vertices[140].x = -88992;
	model->m_vertices[140].y = -254739;
	model->m_vertices[140].z = 69046;

	model->m_vertices[141].x = 103943;
	model->m_vertices[141].y = -122369;
	model->m_vertices[141].z = 86625;

	model->m_vertices[142].x = 44496;
	model->m_vertices[142].y = -130135;
	model->m_vertices[142].z = 140616;

	model->m_vertices[143].x = 88992;
	model->m_vertices[143].y = -254739;
	model->m_vertices[143].z = 69046;

	model->m_vertices[144].x = 0;
	model->m_vertices[144].y = -261578;
	model->m_vertices[144].z = 99863;

	model->m_vertices[145].x = 88992;
	model->m_vertices[145].y = -254739;
	model->m_vertices[145].z = 69046;

	model->m_vertices[146].x = 44496;
	model->m_vertices[146].y = -130135;
	model->m_vertices[146].z = 140616;

	model->m_vertices[147].x = -103943;
	model->m_vertices[147].y = -122369;
	model->m_vertices[147].z = 86625;

	model->m_vertices[148].x = -88992;
	model->m_vertices[148].y = -254739;
	model->m_vertices[148].z = 69046;

	model->m_vertices[149].x = -44496;
	model->m_vertices[149].y = -130135;
	model->m_vertices[149].z = 140616;

	model->m_indices[0] = 0;
	model->m_indices[1] = 1;
	model->m_indices[2] = 2;
	model->m_indices[3] = 3;
	model->m_indices[4] = 4;
	model->m_indices[5] = 5;
	model->m_indices[6] = 6;
	model->m_indices[7] = 7;
	model->m_indices[8] = 8;
	model->m_indices[9] = 9;
	model->m_indices[10] = 10;
	model->m_indices[11] = 11;
	model->m_indices[12] = 12;
	model->m_indices[13] = 13;
	model->m_indices[14] = 14;
	model->m_indices[15] = 15;
	model->m_indices[16] = 16;
	model->m_indices[17] = 17;
	model->m_indices[18] = 18;
	model->m_indices[19] = 19;
	model->m_indices[20] = 20;
	model->m_indices[21] = 21;
	model->m_indices[22] = 22;
	model->m_indices[23] = 23;
	model->m_indices[24] = 24;
	model->m_indices[25] = 25;
	model->m_indices[26] = 26;
	model->m_indices[27] = 27;
	model->m_indices[28] = 28;
	model->m_indices[29] = 29;
	model->m_indices[30] = 30;
	model->m_indices[31] = 31;
	model->m_indices[32] = 32;
	model->m_indices[33] = 33;
	model->m_indices[34] = 34;
	model->m_indices[35] = 35;
	model->m_indices[36] = 36;
	model->m_indices[37] = 37;
	model->m_indices[38] = 38;
	model->m_indices[39] = 39;
	model->m_indices[40] = 40;
	model->m_indices[41] = 41;
	model->m_indices[42] = 42;
	model->m_indices[43] = 43;
	model->m_indices[44] = 44;
	model->m_indices[45] = 45;
	model->m_indices[46] = 46;
	model->m_indices[47] = 47;
	model->m_indices[48] = 48;
	model->m_indices[49] = 49;
	model->m_indices[50] = 50;
	model->m_indices[51] = 51;
	model->m_indices[52] = 52;
	model->m_indices[53] = 53;
	model->m_indices[54] = 54;
	model->m_indices[55] = 55;
	model->m_indices[56] = 56;
	model->m_indices[57] = 57;
	model->m_indices[58] = 58;
	model->m_indices[59] = 59;
	model->m_indices[60] = 60;
	model->m_indices[61] = 61;
	model->m_indices[62] = 62;
	model->m_indices[63] = 63;
	model->m_indices[64] = 64;
	model->m_indices[65] = 65;
	model->m_indices[66] = 66;
	model->m_indices[67] = 67;
	model->m_indices[68] = 68;
	model->m_indices[69] = 69;
	model->m_indices[70] = 70;
	model->m_indices[71] = 71;
	model->m_indices[72] = 72;
	model->m_indices[73] = 73;
	model->m_indices[74] = 74;
	model->m_indices[75] = 75;
	model->m_indices[76] = 76;
	model->m_indices[77] = 77;
	model->m_indices[78] = 78;
	model->m_indices[79] = 79;
	model->m_indices[80] = 80;
	model->m_indices[81] = 81;
	model->m_indices[82] = 82;
	model->m_indices[83] = 83;
	model->m_indices[84] = 84;
	model->m_indices[85] = 85;
	model->m_indices[86] = 86;
	model->m_indices[87] = 87;
	model->m_indices[88] = 88;
	model->m_indices[89] = 89;
	model->m_indices[90] = 90;
	model->m_indices[91] = 91;
	model->m_indices[92] = 92;
	model->m_indices[93] = 93;
	model->m_indices[94] = 94;
	model->m_indices[95] = 95;
	model->m_indices[96] = 96;
	model->m_indices[97] = 97;
	model->m_indices[98] = 98;
	model->m_indices[99] = 99;
	model->m_indices[100] = 100;
	model->m_indices[101] = 101;
	model->m_indices[102] = 102;
	model->m_indices[103] = 103;
	model->m_indices[104] = 104;
	model->m_indices[105] = 105;
	model->m_indices[106] = 106;
	model->m_indices[107] = 107;
	model->m_indices[108] = 108;
	model->m_indices[109] = 109;
	model->m_indices[110] = 110;
	model->m_indices[111] = 111;
	model->m_indices[112] = 112;
	model->m_indices[113] = 113;
	model->m_indices[114] = 114;
	model->m_indices[115] = 115;
	model->m_indices[116] = 116;
	model->m_indices[117] = 117;
	model->m_indices[118] = 118;
	model->m_indices[119] = 119;
	model->m_indices[120] = 120;
	model->m_indices[121] = 121;
	model->m_indices[122] = 122;
	model->m_indices[123] = 123;
	model->m_indices[124] = 124;
	model->m_indices[125] = 125;
	model->m_indices[126] = 126;
	model->m_indices[127] = 127;
	model->m_indices[128] = 128;
	model->m_indices[129] = 129;
	model->m_indices[130] = 130;
	model->m_indices[131] = 131;
	model->m_indices[132] = 132;
	model->m_indices[133] = 133;
	model->m_indices[134] = 134;
	model->m_indices[135] = 135;
	model->m_indices[136] = 136;
	model->m_indices[137] = 137;
	model->m_indices[138] = 138;
	model->m_indices[139] = 139;
	model->m_indices[140] = 140;
	model->m_indices[141] = 141;
	model->m_indices[142] = 142;
	model->m_indices[143] = 143;
	model->m_indices[144] = 144;
	model->m_indices[145] = 145;
	model->m_indices[146] = 146;
	model->m_indices[147] = 147;
	model->m_indices[148] = 148;
	model->m_indices[149] = 149;
	model->m_texCoords[0].u = 2497;
	model->m_texCoords[0].v = -17111;
	model->m_texCoords[1].u = 41228;
	model->m_texCoords[1].v = -17153;
	model->m_texCoords[2].u = 17409;
	model->m_texCoords[2].v = -26672;
	model->m_texCoords[3].u = 39215;
	model->m_texCoords[3].v = -24275;
	model->m_texCoords[4].u = 27508;
	model->m_texCoords[4].v = -29815;
	model->m_texCoords[5].u = 17409;
	model->m_texCoords[5].v = -26672;
	model->m_texCoords[6].u = 49221;
	model->m_texCoords[6].v = -54385;
	model->m_texCoords[7].u = 43912;
	model->m_texCoords[7].v = -45129;
	model->m_texCoords[8].u = 63308;
	model->m_texCoords[8].v = -42473;
	model->m_texCoords[9].u = 41228;
	model->m_texCoords[9].v = -17153;
	model->m_texCoords[10].u = 2497;
	model->m_texCoords[10].v = -17111;
	model->m_texCoords[11].u = 17440;
	model->m_texCoords[11].v = -7612;
	model->m_texCoords[12].u = 39090;
	model->m_texCoords[12].v = -10099;
	model->m_texCoords[13].u = 41228;
	model->m_texCoords[13].v = -17153;
	model->m_texCoords[14].u = 17440;
	model->m_texCoords[14].v = -7612;
	model->m_texCoords[15].u = 39090;
	model->m_texCoords[15].v = -10099;
	model->m_texCoords[16].u = 17440;
	model->m_texCoords[16].v = -7612;
	model->m_texCoords[17].u = 27532;
	model->m_texCoords[17].v = -4631;
	model->m_texCoords[18].u = 63308;
	model->m_texCoords[18].v = -42473;
	model->m_texCoords[19].u = 43912;
	model->m_texCoords[19].v = -45129;
	model->m_texCoords[20].u = 46543;
	model->m_texCoords[20].v = -34795;
	model->m_texCoords[21].u = 17409;
	model->m_texCoords[21].v = -26672;
	model->m_texCoords[22].u = 41228;
	model->m_texCoords[22].v = -17153;
	model->m_texCoords[23].u = 39215;
	model->m_texCoords[23].v = -24275;
	model->m_texCoords[24].u = 38455;
	model->m_texCoords[24].v = -58221;
	model->m_texCoords[25].u = 39295;
	model->m_texCoords[25].v = -52012;
	model->m_texCoords[26].u = 49221;
	model->m_texCoords[26].v = -54385;
	model->m_texCoords[27].u = 43912;
	model->m_texCoords[27].v = -45129;
	model->m_texCoords[28].u = 37644;
	model->m_texCoords[28].v = -39728;
	model->m_texCoords[29].u = 46543;
	model->m_texCoords[29].v = -34795;
	model->m_texCoords[30].u = 39215;
	model->m_texCoords[30].v = -24275;
	model->m_texCoords[31].u = 41228;
	model->m_texCoords[31].v = -17153;
	model->m_texCoords[32].u = 61447;
	model->m_texCoords[32].v = -23410;
	model->m_texCoords[33].u = 27532;
	model->m_texCoords[33].v = -4631;
	model->m_texCoords[34].u = 48107;
	model->m_texCoords[34].v = -1185;
	model->m_texCoords[35].u = 39090;
	model->m_texCoords[35].v = -10099;
	model->m_texCoords[36].u = 60894;
	model->m_texCoords[36].v = -10089;
	model->m_texCoords[37].u = 41228;
	model->m_texCoords[37].v = -17153;
	model->m_texCoords[38].u = 39090;
	model->m_texCoords[38].v = -10099;
	model->m_texCoords[39].u = 16023;
	model->m_texCoords[39].v = -58689;
	model->m_texCoords[40].u = 5866;
	model->m_texCoords[40].v = -57559;
	model->m_texCoords[41].u = 21174;
	model->m_texCoords[41].v = -48166;
	model->m_texCoords[42].u = 13507;
	model->m_texCoords[42].v = -39340;
	model->m_texCoords[43].u = 21174;
	model->m_texCoords[43].v = -48166;
	model->m_texCoords[44].u = 3998;
	model->m_texCoords[44].v = -42999;
	model->m_texCoords[45].u = 61075;
	model->m_texCoords[45].v = -16705;
	model->m_texCoords[46].u = 41228;
	model->m_texCoords[46].v = -17153;
	model->m_texCoords[47].u = 60894;
	model->m_texCoords[47].v = -10089;
	model->m_texCoords[48].u = 2433;
	model->m_texCoords[48].v = -29094;
	model->m_texCoords[49].u = 13467;
	model->m_texCoords[49].v = -29094;
	model->m_texCoords[50].u = 7950;
	model->m_texCoords[50].v = -33925;
	model->m_texCoords[51].u = 41228;
	model->m_texCoords[51].v = -17153;
	model->m_texCoords[52].u = 61075;
	model->m_texCoords[52].v = -16705;
	model->m_texCoords[53].u = 61447;
	model->m_texCoords[53].v = -23410;
	model->m_texCoords[54].u = 3998;
	model->m_texCoords[54].v = -42999;
	model->m_texCoords[55].u = 21174;
	model->m_texCoords[55].v = -48166;
	model->m_texCoords[56].u = 4965;
	model->m_texCoords[56].v = -50270;
	model->m_texCoords[57].u = 21174;
	model->m_texCoords[57].v = -48166;
	model->m_texCoords[58].u = 5866;
	model->m_texCoords[58].v = -57559;
	model->m_texCoords[59].u = 4965;
	model->m_texCoords[59].v = -50270;
	model->m_texCoords[60].u = 14661;
	model->m_texCoords[60].v = -34101;
	model->m_texCoords[61].u = 20178;
	model->m_texCoords[61].v = -29094;
	model->m_texCoords[62].u = 25694;
	model->m_texCoords[62].v = -34101;
	model->m_texCoords[63].u = 37644;
	model->m_texCoords[63].v = -39728;
	model->m_texCoords[64].u = 28849;
	model->m_texCoords[64].v = -39717;
	model->m_texCoords[65].u = 35210;
	model->m_texCoords[65].v = -33989;
	model->m_texCoords[66].u = 16023;
	model->m_texCoords[66].v = -58689;
	model->m_texCoords[67].u = 30793;
	model->m_texCoords[67].v = -54333;
	model->m_texCoords[68].u = 38455;
	model->m_texCoords[68].v = -58221;
	model->m_texCoords[69].u = 27508;
	model->m_texCoords[69].v = -29815;
	model->m_texCoords[70].u = 39215;
	model->m_texCoords[70].v = -24275;
	model->m_texCoords[71].u = 48629;
	model->m_texCoords[71].v = -33250;
	model->m_texCoords[72].u = 52727;
	model->m_texCoords[72].v = -32161;
	model->m_texCoords[73].u = 39215;
	model->m_texCoords[73].v = -24275;
	model->m_texCoords[74].u = 62196;
	model->m_texCoords[74].v = -29340;
	model->m_texCoords[75].u = 61447;
	model->m_texCoords[75].v = -23410;
	model->m_texCoords[76].u = 62196;
	model->m_texCoords[76].v = -29340;
	model->m_texCoords[77].u = 39215;
	model->m_texCoords[77].v = -24275;
	model->m_texCoords[78].u = 16609;
	model->m_texCoords[78].v = -64387;
	model->m_texCoords[79].u = 6521;
	model->m_texCoords[79].v = -63809;
	model->m_texCoords[80].u = 16023;
	model->m_texCoords[80].v = -58689;
	model->m_texCoords[81].u = 48107;
	model->m_texCoords[81].v = -1185;
	model->m_texCoords[82].u = 51953;
	model->m_texCoords[82].v = -2016;
	model->m_texCoords[83].u = 39090;
	model->m_texCoords[83].v = -10099;
	model->m_texCoords[84].u = 3998;
	model->m_texCoords[84].v = -42999;
	model->m_texCoords[85].u = 3104;
	model->m_texCoords[85].v = -36813;
	model->m_texCoords[86].u = 13507;
	model->m_texCoords[86].v = -39340;
	model->m_texCoords[87].u = 51953;
	model->m_texCoords[87].v = -2016;
	model->m_texCoords[88].u = 61198;
	model->m_texCoords[88].v = -4353;
	model->m_texCoords[89].u = 39090;
	model->m_texCoords[89].v = -10099;
	model->m_texCoords[90].u = 39295;
	model->m_texCoords[90].v = -52012;
	model->m_texCoords[91].u = 38493;
	model->m_texCoords[91].v = -45863;
	model->m_texCoords[92].u = 43912;
	model->m_texCoords[92].v = -45129;
	model->m_texCoords[93].u = 30550;
	model->m_texCoords[93].v = -49366;
	model->m_texCoords[94].u = 21174;
	model->m_texCoords[94].v = -48166;
	model->m_texCoords[95].u = 29908;
	model->m_texCoords[95].v = -44573;
	model->m_texCoords[96].u = 37644;
	model->m_texCoords[96].v = -39728;
	model->m_texCoords[97].u = 43912;
	model->m_texCoords[97].v = -45129;
	model->m_texCoords[98].u = 38493;
	model->m_texCoords[98].v = -45863;
	model->m_texCoords[99].u = 29908;
	model->m_texCoords[99].v = -44573;
	model->m_texCoords[100].u = 38493;
	model->m_texCoords[100].v = -45863;
	model->m_texCoords[101].u = 30550;
	model->m_texCoords[101].v = -49366;
	model->m_texCoords[102].u = 21174;
	model->m_texCoords[102].v = -48166;
	model->m_texCoords[103].u = 30550;
	model->m_texCoords[103].v = -49366;
	model->m_texCoords[104].u = 16023;
	model->m_texCoords[104].v = -58689;
	model->m_texCoords[105].u = 30793;
	model->m_texCoords[105].v = -54333;
	model->m_texCoords[106].u = 16023;
	model->m_texCoords[106].v = -58689;
	model->m_texCoords[107].u = 30550;
	model->m_texCoords[107].v = -49366;
	model->m_texCoords[108].u = 21174;
	model->m_texCoords[108].v = -48166;
	model->m_texCoords[109].u = 13507;
	model->m_texCoords[109].v = -39340;
	model->m_texCoords[110].u = 29908;
	model->m_texCoords[110].v = -44573;
	model->m_texCoords[111].u = 29908;
	model->m_texCoords[111].v = -44573;
	model->m_texCoords[112].u = 13507;
	model->m_texCoords[112].v = -39340;
	model->m_texCoords[113].u = 28849;
	model->m_texCoords[113].v = -39717;
	model->m_texCoords[114].u = 39295;
	model->m_texCoords[114].v = -52012;
	model->m_texCoords[115].u = 38455;
	model->m_texCoords[115].v = -58221;
	model->m_texCoords[116].u = 30793;
	model->m_texCoords[116].v = -54333;
	model->m_texCoords[117].u = 13507;
	model->m_texCoords[117].v = -39340;
	model->m_texCoords[118].u = 35210;
	model->m_texCoords[118].v = -33989;
	model->m_texCoords[119].u = 28849;
	model->m_texCoords[119].v = -39717;
	model->m_texCoords[120].u = 60894;
	model->m_texCoords[120].v = -10089;
	model->m_texCoords[121].u = 39090;
	model->m_texCoords[121].v = -10099;
	model->m_texCoords[122].u = 61198;
	model->m_texCoords[122].v = -4353;
	model->m_texCoords[123].u = 48629;
	model->m_texCoords[123].v = -33250;
	model->m_texCoords[124].u = 39215;
	model->m_texCoords[124].v = -24275;
	model->m_texCoords[125].u = 52727;
	model->m_texCoords[125].v = -32161;
	model->m_texCoords[126].u = 35210;
	model->m_texCoords[126].v = -33989;
	model->m_texCoords[127].u = 46543;
	model->m_texCoords[127].v = -34795;
	model->m_texCoords[128].u = 37644;
	model->m_texCoords[128].v = -39728;
	model->m_texCoords[129].u = 43912;
	model->m_texCoords[129].v = -45129;
	model->m_texCoords[130].u = 49221;
	model->m_texCoords[130].v = -54385;
	model->m_texCoords[131].u = 39295;
	model->m_texCoords[131].v = -52012;
	model->m_texCoords[132].u = 5866;
	model->m_texCoords[132].v = -57559;
	model->m_texCoords[133].u = 16023;
	model->m_texCoords[133].v = -58689;
	model->m_texCoords[134].u = 6521;
	model->m_texCoords[134].v = -63809;
	model->m_texCoords[135].u = 12638;
	model->m_texCoords[135].v = -33725;
	model->m_texCoords[136].u = 13507;
	model->m_texCoords[136].v = -39340;
	model->m_texCoords[137].u = 3104;
	model->m_texCoords[137].v = -36813;
	model->m_texCoords[138].u = 38493;
	model->m_texCoords[138].v = -45863;
	model->m_texCoords[139].u = 29908;
	model->m_texCoords[139].v = -44573;
	model->m_texCoords[140].u = 37644;
	model->m_texCoords[140].v = -39728;
	model->m_texCoords[141].u = 30793;
	model->m_texCoords[141].v = -54333;
	model->m_texCoords[142].u = 30550;
	model->m_texCoords[142].v = -49366;
	model->m_texCoords[143].u = 39295;
	model->m_texCoords[143].v = -52012;
	model->m_texCoords[144].u = 38493;
	model->m_texCoords[144].v = -45863;
	model->m_texCoords[145].u = 39295;
	model->m_texCoords[145].v = -52012;
	model->m_texCoords[146].u = 30550;
	model->m_texCoords[146].v = -49366;
	model->m_texCoords[147].u = 28849;
	model->m_texCoords[147].v = -39717;
	model->m_texCoords[148].u = 37644;
	model->m_texCoords[148].v = -39728;
	model->m_texCoords[149].u = 29908;
	model->m_texCoords[149].v = -44573;
	return model;
}
#endif