#ifndef _boat2_
#define _boat2_

#include "RenderData.h"

//This file was auto generated by Model Converter v0.5

RenderData* Getboat2()
{ 
	RenderData* model = new RenderData();
	model->m_numVertices = 192;
	model->m_numIndices = 192;
	model->m_numColorData = 0;
	model->m_numTexCoords = 192;

	model->m_vertices = new Vector3[model->m_numVertices];
	model->m_indices = new uint16[model->m_numIndices];
	model->m_texCoords = new TexCoord2[model->m_numTexCoords];

	model->m_vertices[0].x = 0;
	model->m_vertices[0].y = -767517;
	model->m_vertices[0].z = 5138;

	model->m_vertices[1].x = 0;
	model->m_vertices[1].y = -116532;
	model->m_vertices[1].z = -83920;

	model->m_vertices[2].x = 141557;
	model->m_vertices[2].y = -391358;
	model->m_vertices[2].z = 5138;

	model->m_vertices[3].x = 171981;
	model->m_vertices[3].y = -72336;
	model->m_vertices[3].z = -53213;

	model->m_vertices[4].x = 65871;
	model->m_vertices[4].y = -231737;
	model->m_vertices[4].z = 30194;

	model->m_vertices[5].x = 141557;
	model->m_vertices[5].y = -391358;
	model->m_vertices[5].z = 5138;

	model->m_vertices[6].x = 0;
	model->m_vertices[6].y = -238564;
	model->m_vertices[6].z = 65299;

	model->m_vertices[7].x = 0;
	model->m_vertices[7].y = -391850;
	model->m_vertices[7].z = 23012;

	model->m_vertices[8].x = 65871;
	model->m_vertices[8].y = -231737;
	model->m_vertices[8].z = 30194;

	model->m_vertices[9].x = 235133;
	model->m_vertices[9].y = 247128;
	model->m_vertices[9].z = 43975;

	model->m_vertices[10].x = 199863;
	model->m_vertices[10].y = 17998;
	model->m_vertices[10].z = 43975;

	model->m_vertices[11].x = 236896;
	model->m_vertices[11].y = 193921;
	model->m_vertices[11].z = -28569;

	model->m_vertices[12].x = 171981;
	model->m_vertices[12].y = -72336;
	model->m_vertices[12].z = -53213;

	model->m_vertices[13].x = 128977;
	model->m_vertices[13].y = -15480;
	model->m_vertices[13].z = 57218;

	model->m_vertices[14].x = 65871;
	model->m_vertices[14].y = -231737;
	model->m_vertices[14].z = 30194;

	model->m_vertices[15].x = 199863;
	model->m_vertices[15].y = 17998;
	model->m_vertices[15].z = 43975;

	model->m_vertices[16].x = 93367;
	model->m_vertices[16].y = 254950;
	model->m_vertices[16].z = 49223;

	model->m_vertices[17].x = 128977;
	model->m_vertices[17].y = -15480;
	model->m_vertices[17].z = 57218;

	model->m_vertices[18].x = 199863;
	model->m_vertices[18].y = 17998;
	model->m_vertices[18].z = 43975;

	model->m_vertices[19].x = 171981;
	model->m_vertices[19].y = -72336;
	model->m_vertices[19].z = -53213;

	model->m_vertices[20].x = 236896;
	model->m_vertices[20].y = 34299;
	model->m_vertices[20].z = -28569;

	model->m_vertices[21].x = 148211;
	model->m_vertices[21].y = 321542;
	model->m_vertices[21].z = 18967;

	model->m_vertices[22].x = 149052;
	model->m_vertices[22].y = 322911;
	model->m_vertices[22].z = -27318;

	model->m_vertices[23].x = 93367;
	model->m_vertices[23].y = 254950;
	model->m_vertices[23].z = 49223;

	model->m_vertices[24].x = 235133;
	model->m_vertices[24].y = 247128;
	model->m_vertices[24].z = 43975;

	model->m_vertices[25].x = 177252;
	model->m_vertices[25].y = 321542;
	model->m_vertices[25].z = 20304;

	model->m_vertices[26].x = 93367;
	model->m_vertices[26].y = 254950;
	model->m_vertices[26].z = 49223;

	model->m_vertices[27].x = 0;
	model->m_vertices[27].y = -238564;
	model->m_vertices[27].z = 65299;

	model->m_vertices[28].x = 84341;
	model->m_vertices[28].y = 37039;
	model->m_vertices[28].z = 99400;

	model->m_vertices[29].x = -87604;
	model->m_vertices[29].y = 37039;
	model->m_vertices[29].z = 99400;

	model->m_vertices[30].x = 141557;
	model->m_vertices[30].y = -391358;
	model->m_vertices[30].z = 5138;

	model->m_vertices[31].x = 0;
	model->m_vertices[31].y = -391850;
	model->m_vertices[31].z = 23012;

	model->m_vertices[32].x = 0;
	model->m_vertices[32].y = -767517;
	model->m_vertices[32].z = 5138;

	model->m_vertices[33].x = 0;
	model->m_vertices[33].y = -116532;
	model->m_vertices[33].z = -83920;

	model->m_vertices[34].x = 0;
	model->m_vertices[34].y = -767517;
	model->m_vertices[34].z = 5138;

	model->m_vertices[35].x = -141557;
	model->m_vertices[35].y = -391358;
	model->m_vertices[35].z = 5138;

	model->m_vertices[36].x = -171981;
	model->m_vertices[36].y = -72336;
	model->m_vertices[36].z = -53213;

	model->m_vertices[37].x = 0;
	model->m_vertices[37].y = -116532;
	model->m_vertices[37].z = -83920;

	model->m_vertices[38].x = -141557;
	model->m_vertices[38].y = -391358;
	model->m_vertices[38].z = 5138;

	model->m_vertices[39].x = -171981;
	model->m_vertices[39].y = -72336;
	model->m_vertices[39].z = -53213;

	model->m_vertices[40].x = -141557;
	model->m_vertices[40].y = -391358;
	model->m_vertices[40].z = 5138;

	model->m_vertices[41].x = -65871;
	model->m_vertices[41].y = -231737;
	model->m_vertices[41].z = 30194;

	model->m_vertices[42].x = 0;
	model->m_vertices[42].y = -238564;
	model->m_vertices[42].z = 65299;

	model->m_vertices[43].x = -65871;
	model->m_vertices[43].y = -231737;
	model->m_vertices[43].z = 30194;

	model->m_vertices[44].x = 0;
	model->m_vertices[44].y = -391850;
	model->m_vertices[44].z = 23012;

	model->m_vertices[45].x = -236896;
	model->m_vertices[45].y = 34299;
	model->m_vertices[45].z = -28569;

	model->m_vertices[46].x = -199863;
	model->m_vertices[46].y = 17998;
	model->m_vertices[46].z = 43975;

	model->m_vertices[47].x = -236896;
	model->m_vertices[47].y = 193921;
	model->m_vertices[47].z = -28569;

	model->m_vertices[48].x = -87604;
	model->m_vertices[48].y = 37039;
	model->m_vertices[48].z = 99400;

	model->m_vertices[49].x = -128977;
	model->m_vertices[49].y = -15480;
	model->m_vertices[49].z = 57218;

	model->m_vertices[50].x = -65871;
	model->m_vertices[50].y = -231737;
	model->m_vertices[50].z = 30194;

	model->m_vertices[51].x = -235133;
	model->m_vertices[51].y = 247128;
	model->m_vertices[51].z = 43975;

	model->m_vertices[52].x = -199863;
	model->m_vertices[52].y = 17998;
	model->m_vertices[52].z = 43975;

	model->m_vertices[53].x = -93367;
	model->m_vertices[53].y = 254950;
	model->m_vertices[53].z = 49223;

	model->m_vertices[54].x = -94371;
	model->m_vertices[54].y = 248525;
	model->m_vertices[54].z = -53213;

	model->m_vertices[55].x = -149052;
	model->m_vertices[55].y = 322911;
	model->m_vertices[55].z = -27318;

	model->m_vertices[56].x = -93367;
	model->m_vertices[56].y = 254950;
	model->m_vertices[56].z = 49223;

	model->m_vertices[57].x = -93367;
	model->m_vertices[57].y = 254950;
	model->m_vertices[57].z = 49223;

	model->m_vertices[58].x = -148211;
	model->m_vertices[58].y = 321542;
	model->m_vertices[58].z = 18967;

	model->m_vertices[59].x = -235133;
	model->m_vertices[59].y = 247128;
	model->m_vertices[59].z = 43975;

	model->m_vertices[60].x = -171981;
	model->m_vertices[60].y = -72336;
	model->m_vertices[60].z = -53213;

	model->m_vertices[61].x = -128977;
	model->m_vertices[61].y = -15480;
	model->m_vertices[61].z = 57218;

	model->m_vertices[62].x = -199863;
	model->m_vertices[62].y = 17998;
	model->m_vertices[62].z = 43975;

	model->m_vertices[63].x = 0;
	model->m_vertices[63].y = -767517;
	model->m_vertices[63].z = 5138;

	model->m_vertices[64].x = 0;
	model->m_vertices[64].y = -391850;
	model->m_vertices[64].z = 23012;

	model->m_vertices[65].x = -141557;
	model->m_vertices[65].y = -391358;
	model->m_vertices[65].z = 5138;

	model->m_vertices[66].x = 65871;
	model->m_vertices[66].y = -231737;
	model->m_vertices[66].z = 30194;

	model->m_vertices[67].x = 84341;
	model->m_vertices[67].y = 37039;
	model->m_vertices[67].z = 99400;

	model->m_vertices[68].x = 0;
	model->m_vertices[68].y = -238564;
	model->m_vertices[68].z = 65299;

	model->m_vertices[69].x = -65871;
	model->m_vertices[69].y = -231737;
	model->m_vertices[69].z = 30194;

	model->m_vertices[70].x = 0;
	model->m_vertices[70].y = -238564;
	model->m_vertices[70].z = 65299;

	model->m_vertices[71].x = -87604;
	model->m_vertices[71].y = 37039;
	model->m_vertices[71].z = 99400;

	model->m_vertices[72].x = -93367;
	model->m_vertices[72].y = 254950;
	model->m_vertices[72].z = 49223;

	model->m_vertices[73].x = -87604;
	model->m_vertices[73].y = 37039;
	model->m_vertices[73].z = 99400;

	model->m_vertices[74].x = 0;
	model->m_vertices[74].y = 262773;
	model->m_vertices[74].z = 115550;

	model->m_vertices[75].x = 0;
	model->m_vertices[75].y = 262773;
	model->m_vertices[75].z = 115550;

	model->m_vertices[76].x = 93367;
	model->m_vertices[76].y = 254950;
	model->m_vertices[76].z = 49223;

	model->m_vertices[77].x = 0;
	model->m_vertices[77].y = 484170;
	model->m_vertices[77].z = 113463;

	model->m_vertices[78].x = 141557;
	model->m_vertices[78].y = -391358;
	model->m_vertices[78].z = 5138;

	model->m_vertices[79].x = 0;
	model->m_vertices[79].y = -116532;
	model->m_vertices[79].z = -83920;

	model->m_vertices[80].x = 171981;
	model->m_vertices[80].y = -72336;
	model->m_vertices[80].z = -53213;

	model->m_vertices[81].x = 141557;
	model->m_vertices[81].y = -391358;
	model->m_vertices[81].z = 5138;

	model->m_vertices[82].x = 65871;
	model->m_vertices[82].y = -231737;
	model->m_vertices[82].z = 30194;

	model->m_vertices[83].x = 0;
	model->m_vertices[83].y = -391850;
	model->m_vertices[83].z = 23012;

	model->m_vertices[84].x = 236896;
	model->m_vertices[84].y = 34299;
	model->m_vertices[84].z = -28569;

	model->m_vertices[85].x = 236896;
	model->m_vertices[85].y = 193921;
	model->m_vertices[85].z = -28569;

	model->m_vertices[86].x = 199863;
	model->m_vertices[86].y = 17998;
	model->m_vertices[86].z = 43975;

	model->m_vertices[87].x = 235133;
	model->m_vertices[87].y = 247128;
	model->m_vertices[87].z = 43975;

	model->m_vertices[88].x = 93367;
	model->m_vertices[88].y = 254950;
	model->m_vertices[88].z = 49223;

	model->m_vertices[89].x = 199863;
	model->m_vertices[89].y = 17998;
	model->m_vertices[89].z = 43975;

	model->m_vertices[90].x = 235133;
	model->m_vertices[90].y = 247128;
	model->m_vertices[90].z = 43975;

	model->m_vertices[91].x = 236896;
	model->m_vertices[91].y = 193921;
	model->m_vertices[91].z = -28569;

	model->m_vertices[92].x = 177252;
	model->m_vertices[92].y = 321542;
	model->m_vertices[92].z = 20304;

	model->m_vertices[93].x = 94371;
	model->m_vertices[93].y = 248525;
	model->m_vertices[93].z = -53213;

	model->m_vertices[94].x = 93367;
	model->m_vertices[94].y = 254950;
	model->m_vertices[94].z = 49223;

	model->m_vertices[95].x = 149052;
	model->m_vertices[95].y = 322911;
	model->m_vertices[95].z = -27318;

	model->m_vertices[96].x = 148211;
	model->m_vertices[96].y = 321542;
	model->m_vertices[96].z = 18967;

	model->m_vertices[97].x = 93367;
	model->m_vertices[97].y = 254950;
	model->m_vertices[97].z = 49223;

	model->m_vertices[98].x = 177252;
	model->m_vertices[98].y = 321542;
	model->m_vertices[98].z = 20304;

	model->m_vertices[99].x = -141557;
	model->m_vertices[99].y = -391358;
	model->m_vertices[99].z = 5138;

	model->m_vertices[100].x = 0;
	model->m_vertices[100].y = -391850;
	model->m_vertices[100].z = 23012;

	model->m_vertices[101].x = -65871;
	model->m_vertices[101].y = -231737;
	model->m_vertices[101].z = 30194;

	model->m_vertices[102].x = -235133;
	model->m_vertices[102].y = 247128;
	model->m_vertices[102].z = 43975;

	model->m_vertices[103].x = -236896;
	model->m_vertices[103].y = 193921;
	model->m_vertices[103].z = -28569;

	model->m_vertices[104].x = -199863;
	model->m_vertices[104].y = 17998;
	model->m_vertices[104].z = 43975;

	model->m_vertices[105].x = -199863;
	model->m_vertices[105].y = 17998;
	model->m_vertices[105].z = 43975;

	model->m_vertices[106].x = -236896;
	model->m_vertices[106].y = 34299;
	model->m_vertices[106].z = -28569;

	model->m_vertices[107].x = -171981;
	model->m_vertices[107].y = -72336;
	model->m_vertices[107].z = -53213;

	model->m_vertices[108].x = -94371;
	model->m_vertices[108].y = 248525;
	model->m_vertices[108].z = -53213;

	model->m_vertices[109].x = -236896;
	model->m_vertices[109].y = 193921;
	model->m_vertices[109].z = -28569;

	model->m_vertices[110].x = -149052;
	model->m_vertices[110].y = 322911;
	model->m_vertices[110].z = -27318;

	model->m_vertices[111].x = -148211;
	model->m_vertices[111].y = 321542;
	model->m_vertices[111].z = 18967;

	model->m_vertices[112].x = -93367;
	model->m_vertices[112].y = 254950;
	model->m_vertices[112].z = 49223;

	model->m_vertices[113].x = -149052;
	model->m_vertices[113].y = 322911;
	model->m_vertices[113].z = -27318;

	model->m_vertices[114].x = -177252;
	model->m_vertices[114].y = 321542;
	model->m_vertices[114].z = 20304;

	model->m_vertices[115].x = -235133;
	model->m_vertices[115].y = 247128;
	model->m_vertices[115].z = 43975;

	model->m_vertices[116].x = -148211;
	model->m_vertices[116].y = 321542;
	model->m_vertices[116].z = 18967;

	model->m_vertices[117].x = -87604;
	model->m_vertices[117].y = 37039;
	model->m_vertices[117].z = 99400;

	model->m_vertices[118].x = 84341;
	model->m_vertices[118].y = 37039;
	model->m_vertices[118].z = 99400;

	model->m_vertices[119].x = 0;
	model->m_vertices[119].y = 262773;
	model->m_vertices[119].z = 115550;

	model->m_vertices[120].x = 93367;
	model->m_vertices[120].y = 254950;
	model->m_vertices[120].z = 49223;

	model->m_vertices[121].x = 0;
	model->m_vertices[121].y = 262773;
	model->m_vertices[121].z = 115550;

	model->m_vertices[122].x = 84341;
	model->m_vertices[122].y = 37039;
	model->m_vertices[122].z = 99400;

	model->m_vertices[123].x = 94371;
	model->m_vertices[123].y = 248525;
	model->m_vertices[123].z = -53213;

	model->m_vertices[124].x = 0;
	model->m_vertices[124].y = -116532;
	model->m_vertices[124].z = -83920;

	model->m_vertices[125].x = -94371;
	model->m_vertices[125].y = 248525;
	model->m_vertices[125].z = -53213;

	model->m_vertices[126].x = 0;
	model->m_vertices[126].y = -116532;
	model->m_vertices[126].z = -83920;

	model->m_vertices[127].x = -171981;
	model->m_vertices[127].y = -72336;
	model->m_vertices[127].z = -53213;

	model->m_vertices[128].x = -94371;
	model->m_vertices[128].y = 248525;
	model->m_vertices[128].z = -53213;

	model->m_vertices[129].x = 236896;
	model->m_vertices[129].y = 193921;
	model->m_vertices[129].z = -28569;

	model->m_vertices[130].x = 236896;
	model->m_vertices[130].y = 34299;
	model->m_vertices[130].z = -28569;

	model->m_vertices[131].x = 94371;
	model->m_vertices[131].y = 248525;
	model->m_vertices[131].z = -53213;

	model->m_vertices[132].x = 236896;
	model->m_vertices[132].y = 34299;
	model->m_vertices[132].z = -28569;

	model->m_vertices[133].x = 171981;
	model->m_vertices[133].y = -72336;
	model->m_vertices[133].z = -53213;

	model->m_vertices[134].x = 94371;
	model->m_vertices[134].y = 248525;
	model->m_vertices[134].z = -53213;

	model->m_vertices[135].x = -236896;
	model->m_vertices[135].y = 193921;
	model->m_vertices[135].z = -28569;

	model->m_vertices[136].x = -94371;
	model->m_vertices[136].y = 248525;
	model->m_vertices[136].z = -53213;

	model->m_vertices[137].x = -236896;
	model->m_vertices[137].y = 34299;
	model->m_vertices[137].z = -28569;

	model->m_vertices[138].x = -236896;
	model->m_vertices[138].y = 34299;
	model->m_vertices[138].z = -28569;

	model->m_vertices[139].x = -94371;
	model->m_vertices[139].y = 248525;
	model->m_vertices[139].z = -53213;

	model->m_vertices[140].x = -171981;
	model->m_vertices[140].y = -72336;
	model->m_vertices[140].z = -53213;

	model->m_vertices[141].x = 0;
	model->m_vertices[141].y = -116532;
	model->m_vertices[141].z = -83920;

	model->m_vertices[142].x = 94371;
	model->m_vertices[142].y = 248525;
	model->m_vertices[142].z = -53213;

	model->m_vertices[143].x = 171981;
	model->m_vertices[143].y = -72336;
	model->m_vertices[143].z = -53213;

	model->m_vertices[144].x = 171981;
	model->m_vertices[144].y = -72336;
	model->m_vertices[144].z = -53213;

	model->m_vertices[145].x = 199863;
	model->m_vertices[145].y = 17998;
	model->m_vertices[145].z = 43975;

	model->m_vertices[146].x = 128977;
	model->m_vertices[146].y = -15480;
	model->m_vertices[146].z = 57218;

	model->m_vertices[147].x = 84341;
	model->m_vertices[147].y = 37039;
	model->m_vertices[147].z = 99400;

	model->m_vertices[148].x = 128977;
	model->m_vertices[148].y = -15480;
	model->m_vertices[148].z = 57218;

	model->m_vertices[149].x = 93367;
	model->m_vertices[149].y = 254950;
	model->m_vertices[149].z = 49223;

	model->m_vertices[150].x = -87604;
	model->m_vertices[150].y = 37039;
	model->m_vertices[150].z = 99400;

	model->m_vertices[151].x = -93367;
	model->m_vertices[151].y = 254950;
	model->m_vertices[151].z = 49223;

	model->m_vertices[152].x = -128977;
	model->m_vertices[152].y = -15480;
	model->m_vertices[152].z = 57218;

	model->m_vertices[153].x = -199863;
	model->m_vertices[153].y = 17998;
	model->m_vertices[153].z = 43975;

	model->m_vertices[154].x = -128977;
	model->m_vertices[154].y = -15480;
	model->m_vertices[154].z = 57218;

	model->m_vertices[155].x = -93367;
	model->m_vertices[155].y = 254950;
	model->m_vertices[155].z = 49223;

	model->m_vertices[156].x = -171981;
	model->m_vertices[156].y = -72336;
	model->m_vertices[156].z = -53213;

	model->m_vertices[157].x = -65871;
	model->m_vertices[157].y = -231737;
	model->m_vertices[157].z = 30194;

	model->m_vertices[158].x = -128977;
	model->m_vertices[158].y = -15480;
	model->m_vertices[158].z = 57218;

	model->m_vertices[159].x = 84341;
	model->m_vertices[159].y = 37039;
	model->m_vertices[159].z = 99400;

	model->m_vertices[160].x = 65871;
	model->m_vertices[160].y = -231737;
	model->m_vertices[160].z = 30194;

	model->m_vertices[161].x = 128977;
	model->m_vertices[161].y = -15480;
	model->m_vertices[161].z = 57218;

	model->m_vertices[162].x = -148211;
	model->m_vertices[162].y = 321542;
	model->m_vertices[162].z = 18967;

	model->m_vertices[163].x = -149052;
	model->m_vertices[163].y = 322911;
	model->m_vertices[163].z = -27318;

	model->m_vertices[164].x = -177252;
	model->m_vertices[164].y = 321542;
	model->m_vertices[164].z = 20304;

	model->m_vertices[165].x = -235133;
	model->m_vertices[165].y = 247128;
	model->m_vertices[165].z = 43975;

	model->m_vertices[166].x = -177252;
	model->m_vertices[166].y = 321542;
	model->m_vertices[166].z = 20304;

	model->m_vertices[167].x = -236896;
	model->m_vertices[167].y = 193921;
	model->m_vertices[167].z = -28569;

	model->m_vertices[168].x = -149052;
	model->m_vertices[168].y = 322911;
	model->m_vertices[168].z = -27318;

	model->m_vertices[169].x = -236896;
	model->m_vertices[169].y = 193921;
	model->m_vertices[169].z = -28569;

	model->m_vertices[170].x = -177252;
	model->m_vertices[170].y = 321542;
	model->m_vertices[170].z = 20304;

	model->m_vertices[171].x = 148211;
	model->m_vertices[171].y = 321542;
	model->m_vertices[171].z = 18967;

	model->m_vertices[172].x = 177252;
	model->m_vertices[172].y = 321542;
	model->m_vertices[172].z = 20304;

	model->m_vertices[173].x = 149052;
	model->m_vertices[173].y = 322911;
	model->m_vertices[173].z = -27318;

	model->m_vertices[174].x = 94371;
	model->m_vertices[174].y = 248525;
	model->m_vertices[174].z = -53213;

	model->m_vertices[175].x = 149052;
	model->m_vertices[175].y = 322911;
	model->m_vertices[175].z = -27318;

	model->m_vertices[176].x = 236896;
	model->m_vertices[176].y = 193921;
	model->m_vertices[176].z = -28569;

	model->m_vertices[177].x = 177252;
	model->m_vertices[177].y = 321542;
	model->m_vertices[177].z = 20304;

	model->m_vertices[178].x = 236896;
	model->m_vertices[178].y = 193921;
	model->m_vertices[178].z = -28569;

	model->m_vertices[179].x = 149052;
	model->m_vertices[179].y = 322911;
	model->m_vertices[179].z = -27318;

	model->m_vertices[180].x = 93367;
	model->m_vertices[180].y = 254950;
	model->m_vertices[180].z = 49223;

	model->m_vertices[181].x = 94371;
	model->m_vertices[181].y = 248525;
	model->m_vertices[181].z = -53213;

	model->m_vertices[182].x = 0;
	model->m_vertices[182].y = 484170;
	model->m_vertices[182].z = 113463;

	model->m_vertices[183].x = 0;
	model->m_vertices[183].y = 262773;
	model->m_vertices[183].z = 115550;

	model->m_vertices[184].x = 0;
	model->m_vertices[184].y = 484170;
	model->m_vertices[184].z = 113463;

	model->m_vertices[185].x = -93367;
	model->m_vertices[185].y = 254950;
	model->m_vertices[185].z = 49223;

	model->m_vertices[186].x = 94371;
	model->m_vertices[186].y = 248525;
	model->m_vertices[186].z = -53213;

	model->m_vertices[187].x = -94371;
	model->m_vertices[187].y = 248525;
	model->m_vertices[187].z = -53213;

	model->m_vertices[188].x = 0;
	model->m_vertices[188].y = 484170;
	model->m_vertices[188].z = 113463;

	model->m_vertices[189].x = -93367;
	model->m_vertices[189].y = 254950;
	model->m_vertices[189].z = 49223;

	model->m_vertices[190].x = 0;
	model->m_vertices[190].y = 484170;
	model->m_vertices[190].z = 113463;

	model->m_vertices[191].x = -94371;
	model->m_vertices[191].y = 248525;
	model->m_vertices[191].z = -53213;

	model->m_indices[0] = 0;
	model->m_indices[1] = 1;
	model->m_indices[2] = 2;
	model->m_indices[3] = 3;
	model->m_indices[4] = 4;
	model->m_indices[5] = 5;
	model->m_indices[6] = 6;
	model->m_indices[7] = 7;
	model->m_indices[8] = 8;
	model->m_indices[9] = 9;
	model->m_indices[10] = 10;
	model->m_indices[11] = 11;
	model->m_indices[12] = 12;
	model->m_indices[13] = 13;
	model->m_indices[14] = 14;
	model->m_indices[15] = 15;
	model->m_indices[16] = 16;
	model->m_indices[17] = 17;
	model->m_indices[18] = 18;
	model->m_indices[19] = 19;
	model->m_indices[20] = 20;
	model->m_indices[21] = 21;
	model->m_indices[22] = 22;
	model->m_indices[23] = 23;
	model->m_indices[24] = 24;
	model->m_indices[25] = 25;
	model->m_indices[26] = 26;
	model->m_indices[27] = 27;
	model->m_indices[28] = 28;
	model->m_indices[29] = 29;
	model->m_indices[30] = 30;
	model->m_indices[31] = 31;
	model->m_indices[32] = 32;
	model->m_indices[33] = 33;
	model->m_indices[34] = 34;
	model->m_indices[35] = 35;
	model->m_indices[36] = 36;
	model->m_indices[37] = 37;
	model->m_indices[38] = 38;
	model->m_indices[39] = 39;
	model->m_indices[40] = 40;
	model->m_indices[41] = 41;
	model->m_indices[42] = 42;
	model->m_indices[43] = 43;
	model->m_indices[44] = 44;
	model->m_indices[45] = 45;
	model->m_indices[46] = 46;
	model->m_indices[47] = 47;
	model->m_indices[48] = 48;
	model->m_indices[49] = 49;
	model->m_indices[50] = 50;
	model->m_indices[51] = 51;
	model->m_indices[52] = 52;
	model->m_indices[53] = 53;
	model->m_indices[54] = 54;
	model->m_indices[55] = 55;
	model->m_indices[56] = 56;
	model->m_indices[57] = 57;
	model->m_indices[58] = 58;
	model->m_indices[59] = 59;
	model->m_indices[60] = 60;
	model->m_indices[61] = 61;
	model->m_indices[62] = 62;
	model->m_indices[63] = 63;
	model->m_indices[64] = 64;
	model->m_indices[65] = 65;
	model->m_indices[66] = 66;
	model->m_indices[67] = 67;
	model->m_indices[68] = 68;
	model->m_indices[69] = 69;
	model->m_indices[70] = 70;
	model->m_indices[71] = 71;
	model->m_indices[72] = 72;
	model->m_indices[73] = 73;
	model->m_indices[74] = 74;
	model->m_indices[75] = 75;
	model->m_indices[76] = 76;
	model->m_indices[77] = 77;
	model->m_indices[78] = 78;
	model->m_indices[79] = 79;
	model->m_indices[80] = 80;
	model->m_indices[81] = 81;
	model->m_indices[82] = 82;
	model->m_indices[83] = 83;
	model->m_indices[84] = 84;
	model->m_indices[85] = 85;
	model->m_indices[86] = 86;
	model->m_indices[87] = 87;
	model->m_indices[88] = 88;
	model->m_indices[89] = 89;
	model->m_indices[90] = 90;
	model->m_indices[91] = 91;
	model->m_indices[92] = 92;
	model->m_indices[93] = 93;
	model->m_indices[94] = 94;
	model->m_indices[95] = 95;
	model->m_indices[96] = 96;
	model->m_indices[97] = 97;
	model->m_indices[98] = 98;
	model->m_indices[99] = 99;
	model->m_indices[100] = 100;
	model->m_indices[101] = 101;
	model->m_indices[102] = 102;
	model->m_indices[103] = 103;
	model->m_indices[104] = 104;
	model->m_indices[105] = 105;
	model->m_indices[106] = 106;
	model->m_indices[107] = 107;
	model->m_indices[108] = 108;
	model->m_indices[109] = 109;
	model->m_indices[110] = 110;
	model->m_indices[111] = 111;
	model->m_indices[112] = 112;
	model->m_indices[113] = 113;
	model->m_indices[114] = 114;
	model->m_indices[115] = 115;
	model->m_indices[116] = 116;
	model->m_indices[117] = 117;
	model->m_indices[118] = 118;
	model->m_indices[119] = 119;
	model->m_indices[120] = 120;
	model->m_indices[121] = 121;
	model->m_indices[122] = 122;
	model->m_indices[123] = 123;
	model->m_indices[124] = 124;
	model->m_indices[125] = 125;
	model->m_indices[126] = 126;
	model->m_indices[127] = 127;
	model->m_indices[128] = 128;
	model->m_indices[129] = 129;
	model->m_indices[130] = 130;
	model->m_indices[131] = 131;
	model->m_indices[132] = 132;
	model->m_indices[133] = 133;
	model->m_indices[134] = 134;
	model->m_indices[135] = 135;
	model->m_indices[136] = 136;
	model->m_indices[137] = 137;
	model->m_indices[138] = 138;
	model->m_indices[139] = 139;
	model->m_indices[140] = 140;
	model->m_indices[141] = 141;
	model->m_indices[142] = 142;
	model->m_indices[143] = 143;
	model->m_indices[144] = 144;
	model->m_indices[145] = 145;
	model->m_indices[146] = 146;
	model->m_indices[147] = 147;
	model->m_indices[148] = 148;
	model->m_indices[149] = 149;
	model->m_indices[150] = 150;
	model->m_indices[151] = 151;
	model->m_indices[152] = 152;
	model->m_indices[153] = 153;
	model->m_indices[154] = 154;
	model->m_indices[155] = 155;
	model->m_indices[156] = 156;
	model->m_indices[157] = 157;
	model->m_indices[158] = 158;
	model->m_indices[159] = 159;
	model->m_indices[160] = 160;
	model->m_indices[161] = 161;
	model->m_indices[162] = 162;
	model->m_indices[163] = 163;
	model->m_indices[164] = 164;
	model->m_indices[165] = 165;
	model->m_indices[166] = 166;
	model->m_indices[167] = 167;
	model->m_indices[168] = 168;
	model->m_indices[169] = 169;
	model->m_indices[170] = 170;
	model->m_indices[171] = 171;
	model->m_indices[172] = 172;
	model->m_indices[173] = 173;
	model->m_indices[174] = 174;
	model->m_indices[175] = 175;
	model->m_indices[176] = 176;
	model->m_indices[177] = 177;
	model->m_indices[178] = 178;
	model->m_indices[179] = 179;
	model->m_indices[180] = 180;
	model->m_indices[181] = 181;
	model->m_indices[182] = 182;
	model->m_indices[183] = 183;
	model->m_indices[184] = 184;
	model->m_indices[185] = 185;
	model->m_indices[186] = 186;
	model->m_indices[187] = 187;
	model->m_indices[188] = 188;
	model->m_indices[189] = 189;
	model->m_indices[190] = 190;
	model->m_indices[191] = 191;
	model->m_texCoords[0].u = 34450;
	model->m_texCoords[0].v = -65536;
	model->m_texCoords[1].u = 33180;
	model->m_texCoords[1].v = -26443;
	model->m_texCoords[2].u = 14248;
	model->m_texCoords[2].v = -44842;
	model->m_texCoords[3].u = 9430;
	model->m_texCoords[3].v = -25204;
	model->m_texCoords[4].u = 24378;
	model->m_texCoords[4].v = -36806;
	model->m_texCoords[5].u = 14248;
	model->m_texCoords[5].v = -44842;
	model->m_texCoords[6].u = 33476;
	model->m_texCoords[6].v = -38336;
	model->m_texCoords[7].u = 33747;
	model->m_texCoords[7].v = -45362;
	model->m_texCoords[8].u = 24378;
	model->m_texCoords[8].v = -36806;
	model->m_texCoords[9].u = 173;
	model->m_texCoords[9].v = -10928;
	model->m_texCoords[10].u = 5463;
	model->m_texCoords[10].v = -23577;
	model->m_texCoords[11].u = 0;
	model->m_texCoords[11].v = -11375;
	model->m_texCoords[12].u = 9430;
	model->m_texCoords[12].v = -25204;
	model->m_texCoords[13].u = 15292;
	model->m_texCoords[13].v = -25825;
	model->m_texCoords[14].u = 24378;
	model->m_texCoords[14].v = -36806;
	model->m_texCoords[15].u = 5463;
	model->m_texCoords[15].v = -23577;
	model->m_texCoords[16].u = 19680;
	model->m_texCoords[16].v = -10553;
	model->m_texCoords[17].u = 15292;
	model->m_texCoords[17].v = -25825;
	model->m_texCoords[18].u = 5463;
	model->m_texCoords[18].v = -23577;
	model->m_texCoords[19].u = 9430;
	model->m_texCoords[19].v = -25204;
	model->m_texCoords[20].u = 302;
	model->m_texCoords[20].v = -20209;
	model->m_texCoords[21].u = 11989;
	model->m_texCoords[21].v = -5873;
	model->m_texCoords[22].u = 11851;
	model->m_texCoords[22].v = -4204;
	model->m_texCoords[23].u = 19680;
	model->m_texCoords[23].v = -10553;
	model->m_texCoords[24].u = 173;
	model->m_texCoords[24].v = -10928;
	model->m_texCoords[25].u = 7992;
	model->m_texCoords[25].v = -5944;
	model->m_texCoords[26].u = 19680;
	model->m_texCoords[26].v = -10553;
	model->m_texCoords[27].u = 33476;
	model->m_texCoords[27].v = -38336;
	model->m_texCoords[28].u = 21131;
	model->m_texCoords[28].v = -24650;
	model->m_texCoords[29].u = 44805;
	model->m_texCoords[29].v = -24500;
	model->m_texCoords[30].u = 14248;
	model->m_texCoords[30].v = -44842;
	model->m_texCoords[31].u = 33747;
	model->m_texCoords[31].v = -45362;
	model->m_texCoords[32].u = 34450;
	model->m_texCoords[32].v = -65536;
	model->m_texCoords[33].u = 33180;
	model->m_texCoords[33].v = -26443;
	model->m_texCoords[34].u = 34450;
	model->m_texCoords[34].v = -65536;
	model->m_texCoords[35].u = 53229;
	model->m_texCoords[35].v = -44596;
	model->m_texCoords[36].u = 56789;
	model->m_texCoords[36].v = -24905;
	model->m_texCoords[37].u = 33180;
	model->m_texCoords[37].v = -26443;
	model->m_texCoords[38].u = 53229;
	model->m_texCoords[38].v = -44596;
	model->m_texCoords[39].u = 56789;
	model->m_texCoords[39].v = -24905;
	model->m_texCoords[40].u = 53229;
	model->m_texCoords[40].v = -44596;
	model->m_texCoords[41].u = 42517;
	model->m_texCoords[41].v = -36692;
	model->m_texCoords[42].u = 33476;
	model->m_texCoords[42].v = -38336;
	model->m_texCoords[43].u = 42517;
	model->m_texCoords[43].v = -36692;
	model->m_texCoords[44].u = 33747;
	model->m_texCoords[44].v = -45362;
	model->m_texCoords[45].u = 65536;
	model->m_texCoords[45].v = -19796;
	model->m_texCoords[46].u = 60499;
	model->m_texCoords[46].v = -23230;
	model->m_texCoords[47].u = 65233;
	model->m_texCoords[47].v = -10963;
	model->m_texCoords[48].u = 44805;
	model->m_texCoords[48].v = -24500;
	model->m_texCoords[49].u = 50808;
	model->m_texCoords[49].v = -25600;
	model->m_texCoords[50].u = 42517;
	model->m_texCoords[50].v = -36692;
	model->m_texCoords[51].u = 64922;
	model->m_texCoords[51].v = -10519;
	model->m_texCoords[52].u = 60499;
	model->m_texCoords[52].v = -23230;
	model->m_texCoords[53].u = 45390;
	model->m_texCoords[53].v = -10390;
	model->m_texCoords[54].u = 45496;
	model->m_texCoords[54].v = -7216;
	model->m_texCoords[55].u = 52895;
	model->m_texCoords[55].v = -3944;
	model->m_texCoords[56].u = 45390;
	model->m_texCoords[56].v = -10390;
	model->m_texCoords[57].u = 45390;
	model->m_texCoords[57].v = -10390;
	model->m_texCoords[58].u = 52802;
	model->m_texCoords[58].v = -5615;
	model->m_texCoords[59].u = 64922;
	model->m_texCoords[59].v = -10519;
	model->m_texCoords[60].u = 56789;
	model->m_texCoords[60].v = -24905;
	model->m_texCoords[61].u = 50808;
	model->m_texCoords[61].v = -25600;
	model->m_texCoords[62].u = 60499;
	model->m_texCoords[62].v = -23230;
	model->m_texCoords[63].u = 34450;
	model->m_texCoords[63].v = -65536;
	model->m_texCoords[64].u = 33747;
	model->m_texCoords[64].v = -45362;
	model->m_texCoords[65].u = 53229;
	model->m_texCoords[65].v = -44596;
	model->m_texCoords[66].u = 24378;
	model->m_texCoords[66].v = -36806;
	model->m_texCoords[67].u = 21131;
	model->m_texCoords[67].v = -24650;
	model->m_texCoords[68].u = 33476;
	model->m_texCoords[68].v = -38336;
	model->m_texCoords[69].u = 42517;
	model->m_texCoords[69].v = -36692;
	model->m_texCoords[70].u = 33476;
	model->m_texCoords[70].v = -38336;
	model->m_texCoords[71].u = 44805;
	model->m_texCoords[71].v = -24500;
	model->m_texCoords[72].u = 45390;
	model->m_texCoords[72].v = -10390;
	model->m_texCoords[73].u = 44805;
	model->m_texCoords[73].v = -24500;
	model->m_texCoords[74].u = 32549;
	model->m_texCoords[74].v = -12323;
	model->m_texCoords[75].u = 32549;
	model->m_texCoords[75].v = -12323;
	model->m_texCoords[76].u = 19680;
	model->m_texCoords[76].v = -10553;
	model->m_texCoords[77].u = 32130;
	model->m_texCoords[77].v = 0;
	model->m_texCoords[78].u = 14248;
	model->m_texCoords[78].v = -44842;
	model->m_texCoords[79].u = 33180;
	model->m_texCoords[79].v = -26443;
	model->m_texCoords[80].u = 9430;
	model->m_texCoords[80].v = -25204;
	model->m_texCoords[81].u = 14248;
	model->m_texCoords[81].v = -44842;
	model->m_texCoords[82].u = 24378;
	model->m_texCoords[82].v = -36806;
	model->m_texCoords[83].u = 33747;
	model->m_texCoords[83].v = -45362;
	model->m_texCoords[84].u = 302;
	model->m_texCoords[84].v = -20209;
	model->m_texCoords[85].u = 0;
	model->m_texCoords[85].v = -11375;
	model->m_texCoords[86].u = 5463;
	model->m_texCoords[86].v = -23577;
	model->m_texCoords[87].u = 173;
	model->m_texCoords[87].v = -10928;
	model->m_texCoords[88].u = 19680;
	model->m_texCoords[88].v = -10553;
	model->m_texCoords[89].u = 5463;
	model->m_texCoords[89].v = -23577;
	model->m_texCoords[90].u = 173;
	model->m_texCoords[90].v = -10928;
	model->m_texCoords[91].u = 0;
	model->m_texCoords[91].v = -11375;
	model->m_texCoords[92].u = 7992;
	model->m_texCoords[92].v = -5944;
	model->m_texCoords[93].u = 19509;
	model->m_texCoords[93].v = -7381;
	model->m_texCoords[94].u = 19680;
	model->m_texCoords[94].v = -10553;
	model->m_texCoords[95].u = 11851;
	model->m_texCoords[95].v = -4204;
	model->m_texCoords[96].u = 11989;
	model->m_texCoords[96].v = -5873;
	model->m_texCoords[97].u = 19680;
	model->m_texCoords[97].v = -10553;
	model->m_texCoords[98].u = 7992;
	model->m_texCoords[98].v = -5944;
	model->m_texCoords[99].u = 53229;
	model->m_texCoords[99].v = -44596;
	model->m_texCoords[100].u = 33747;
	model->m_texCoords[100].v = -45362;
	model->m_texCoords[101].u = 42517;
	model->m_texCoords[101].v = -36692;
	model->m_texCoords[102].u = 64922;
	model->m_texCoords[102].v = -10519;
	model->m_texCoords[103].u = 65233;
	model->m_texCoords[103].v = -10963;
	model->m_texCoords[104].u = 60499;
	model->m_texCoords[104].v = -23230;
	model->m_texCoords[105].u = 60499;
	model->m_texCoords[105].v = -23230;
	model->m_texCoords[106].u = 65536;
	model->m_texCoords[106].v = -19796;
	model->m_texCoords[107].u = 56789;
	model->m_texCoords[107].v = -24905;
	model->m_texCoords[108].u = 45496;
	model->m_texCoords[108].v = -7216;
	model->m_texCoords[109].u = 65233;
	model->m_texCoords[109].v = -10963;
	model->m_texCoords[110].u = 52895;
	model->m_texCoords[110].v = -3944;
	model->m_texCoords[111].u = 52802;
	model->m_texCoords[111].v = -5615;
	model->m_texCoords[112].u = 45390;
	model->m_texCoords[112].v = -10390;
	model->m_texCoords[113].u = 52895;
	model->m_texCoords[113].v = -3944;
	model->m_texCoords[114].u = 56801;
	model->m_texCoords[114].v = -5636;
	model->m_texCoords[115].u = 64922;
	model->m_texCoords[115].v = -10519;
	model->m_texCoords[116].u = 52802;
	model->m_texCoords[116].v = -5615;
	model->m_texCoords[117].u = 44805;
	model->m_texCoords[117].v = -24500;
	model->m_texCoords[118].u = 21131;
	model->m_texCoords[118].v = -24650;
	model->m_texCoords[119].u = 32549;
	model->m_texCoords[119].v = -12323;
	model->m_texCoords[120].u = 19680;
	model->m_texCoords[120].v = -10553;
	model->m_texCoords[121].u = 32549;
	model->m_texCoords[121].v = -12323;
	model->m_texCoords[122].u = 21131;
	model->m_texCoords[122].v = -24650;
	model->m_texCoords[123].u = 19509;
	model->m_texCoords[123].v = -7381;
	model->m_texCoords[124].u = 33180;
	model->m_texCoords[124].v = -26443;
	model->m_texCoords[125].u = 45496;
	model->m_texCoords[125].v = -7216;
	model->m_texCoords[126].u = 33180;
	model->m_texCoords[126].v = -26443;
	model->m_texCoords[127].u = 56789;
	model->m_texCoords[127].v = -24905;
	model->m_texCoords[128].u = 45496;
	model->m_texCoords[128].v = -7216;
	model->m_texCoords[129].u = 0;
	model->m_texCoords[129].v = -11375;
	model->m_texCoords[130].u = 302;
	model->m_texCoords[130].v = -20209;
	model->m_texCoords[131].u = 19509;
	model->m_texCoords[131].v = -7381;
	model->m_texCoords[132].u = 302;
	model->m_texCoords[132].v = -20209;
	model->m_texCoords[133].u = 9430;
	model->m_texCoords[133].v = -25204;
	model->m_texCoords[134].u = 19509;
	model->m_texCoords[134].v = -7381;
	model->m_texCoords[135].u = 65233;
	model->m_texCoords[135].v = -10963;
	model->m_texCoords[136].u = 45496;
	model->m_texCoords[136].v = -7216;
	model->m_texCoords[137].u = 65536;
	model->m_texCoords[137].v = -19796;
	model->m_texCoords[138].u = 65536;
	model->m_texCoords[138].v = -19796;
	model->m_texCoords[139].u = 45496;
	model->m_texCoords[139].v = -7216;
	model->m_texCoords[140].u = 56789;
	model->m_texCoords[140].v = -24905;
	model->m_texCoords[141].u = 33180;
	model->m_texCoords[141].v = -26443;
	model->m_texCoords[142].u = 19509;
	model->m_texCoords[142].v = -7381;
	model->m_texCoords[143].u = 9430;
	model->m_texCoords[143].v = -25204;
	model->m_texCoords[144].u = 9430;
	model->m_texCoords[144].v = -25204;
	model->m_texCoords[145].u = 5463;
	model->m_texCoords[145].v = -23577;
	model->m_texCoords[146].u = 15292;
	model->m_texCoords[146].v = -25825;
	model->m_texCoords[147].u = 21131;
	model->m_texCoords[147].v = -24650;
	model->m_texCoords[148].u = 15292;
	model->m_texCoords[148].v = -25825;
	model->m_texCoords[149].u = 19680;
	model->m_texCoords[149].v = -10553;
	model->m_texCoords[150].u = 44805;
	model->m_texCoords[150].v = -24500;
	model->m_texCoords[151].u = 45390;
	model->m_texCoords[151].v = -10390;
	model->m_texCoords[152].u = 50808;
	model->m_texCoords[152].v = -25600;
	model->m_texCoords[153].u = 60499;
	model->m_texCoords[153].v = -23230;
	model->m_texCoords[154].u = 50808;
	model->m_texCoords[154].v = -25600;
	model->m_texCoords[155].u = 45390;
	model->m_texCoords[155].v = -10390;
	model->m_texCoords[156].u = 56789;
	model->m_texCoords[156].v = -24905;
	model->m_texCoords[157].u = 42517;
	model->m_texCoords[157].v = -36692;
	model->m_texCoords[158].u = 50808;
	model->m_texCoords[158].v = -25600;
	model->m_texCoords[159].u = 21131;
	model->m_texCoords[159].v = -24650;
	model->m_texCoords[160].u = 24378;
	model->m_texCoords[160].v = -36806;
	model->m_texCoords[161].u = 15292;
	model->m_texCoords[161].v = -25825;
	model->m_texCoords[162].u = 52802;
	model->m_texCoords[162].v = -5615;
	model->m_texCoords[163].u = 52895;
	model->m_texCoords[163].v = -3944;
	model->m_texCoords[164].u = 56801;
	model->m_texCoords[164].v = -5636;
	model->m_texCoords[165].u = 64922;
	model->m_texCoords[165].v = -10519;
	model->m_texCoords[166].u = 56801;
	model->m_texCoords[166].v = -5636;
	model->m_texCoords[167].u = 65233;
	model->m_texCoords[167].v = -10963;
	model->m_texCoords[168].u = 52895;
	model->m_texCoords[168].v = -3944;
	model->m_texCoords[169].u = 65233;
	model->m_texCoords[169].v = -10963;
	model->m_texCoords[170].u = 56801;
	model->m_texCoords[170].v = -5636;
	model->m_texCoords[171].u = 11989;
	model->m_texCoords[171].v = -5873;
	model->m_texCoords[172].u = 7992;
	model->m_texCoords[172].v = -5944;
	model->m_texCoords[173].u = 11851;
	model->m_texCoords[173].v = -4204;
	model->m_texCoords[174].u = 19509;
	model->m_texCoords[174].v = -7381;
	model->m_texCoords[175].u = 11851;
	model->m_texCoords[175].v = -4204;
	model->m_texCoords[176].u = 0;
	model->m_texCoords[176].v = -11375;
	model->m_texCoords[177].u = 7992;
	model->m_texCoords[177].v = -5944;
	model->m_texCoords[178].u = 0;
	model->m_texCoords[178].v = -11375;
	model->m_texCoords[179].u = 11851;
	model->m_texCoords[179].v = -4204;
	model->m_texCoords[180].u = 19680;
	model->m_texCoords[180].v = -10553;
	model->m_texCoords[181].u = 19509;
	model->m_texCoords[181].v = -7381;
	model->m_texCoords[182].u = 32130;
	model->m_texCoords[182].v = 0;
	model->m_texCoords[183].u = 32549;
	model->m_texCoords[183].v = -12323;
	model->m_texCoords[184].u = 32130;
	model->m_texCoords[184].v = 0;
	model->m_texCoords[185].u = 45390;
	model->m_texCoords[185].v = -10390;
	model->m_texCoords[186].u = 19509;
	model->m_texCoords[186].v = -7381;
	model->m_texCoords[187].u = 45496;
	model->m_texCoords[187].v = -7216;
	model->m_texCoords[188].u = 32130;
	model->m_texCoords[188].v = 0;
	model->m_texCoords[189].u = 45390;
	model->m_texCoords[189].v = -10390;
	model->m_texCoords[190].u = 32130;
	model->m_texCoords[190].v = 0;
	model->m_texCoords[191].u = 45496;
	model->m_texCoords[191].v = -7216;
	return model;
}
#endif