#ifndef _checkpoint_
#define _checkpoint_

#include "RenderData.h"

//This file was auto generated by Model Converter v0.5

RenderData* Getcheckpoint()
{ 
	RenderData* model = new RenderData();
	model->m_numVertices = 24;
	model->m_numIndices = 24;
	model->m_numColorData = 0;
	model->m_numTexCoords = 24;

	model->m_vertices = new Vector3[model->m_numVertices];
	model->m_indices = new uint16[model->m_numIndices];
	model->m_texCoords = new TexCoord2[model->m_numTexCoords];

	model->m_vertices[0].x = -485;
	model->m_vertices[0].y = -103;
	model->m_vertices[0].z = 92680;

	model->m_vertices[1].x = 76679;
	model->m_vertices[1].y = -74240;
	model->m_vertices[1].z = 341;

	model->m_vertices[2].x = 76799;
	model->m_vertices[2].y = 74007;
	model->m_vertices[2].z = 462;

	model->m_vertices[3].x = 76799;
	model->m_vertices[3].y = 74007;
	model->m_vertices[3].z = 462;

	model->m_vertices[4].x = 76679;
	model->m_vertices[4].y = -74240;
	model->m_vertices[4].z = 341;

	model->m_vertices[5].x = 485;
	model->m_vertices[5].y = 103;
	model->m_vertices[5].z = -92680;

	model->m_vertices[6].x = -485;
	model->m_vertices[6].y = -103;
	model->m_vertices[6].z = 92680;

	model->m_vertices[7].x = -76799;
	model->m_vertices[7].y = -74007;
	model->m_vertices[7].z = -462;

	model->m_vertices[8].x = 76679;
	model->m_vertices[8].y = -74240;
	model->m_vertices[8].z = 341;

	model->m_vertices[9].x = 485;
	model->m_vertices[9].y = 103;
	model->m_vertices[9].z = -92680;

	model->m_vertices[10].x = -76679;
	model->m_vertices[10].y = 74240;
	model->m_vertices[10].z = -341;

	model->m_vertices[11].x = 76799;
	model->m_vertices[11].y = 74007;
	model->m_vertices[11].z = 462;

	model->m_vertices[12].x = -76799;
	model->m_vertices[12].y = -74007;
	model->m_vertices[12].z = -462;

	model->m_vertices[13].x = -76679;
	model->m_vertices[13].y = 74240;
	model->m_vertices[13].z = -341;

	model->m_vertices[14].x = 485;
	model->m_vertices[14].y = 103;
	model->m_vertices[14].z = -92680;

	model->m_vertices[15].x = -485;
	model->m_vertices[15].y = -103;
	model->m_vertices[15].z = 92680;

	model->m_vertices[16].x = -76679;
	model->m_vertices[16].y = 74240;
	model->m_vertices[16].z = -341;

	model->m_vertices[17].x = -76799;
	model->m_vertices[17].y = -74007;
	model->m_vertices[17].z = -462;

	model->m_vertices[18].x = 485;
	model->m_vertices[18].y = 103;
	model->m_vertices[18].z = -92680;

	model->m_vertices[19].x = 76679;
	model->m_vertices[19].y = -74240;
	model->m_vertices[19].z = 341;

	model->m_vertices[20].x = -76799;
	model->m_vertices[20].y = -74007;
	model->m_vertices[20].z = -462;

	model->m_vertices[21].x = -485;
	model->m_vertices[21].y = -103;
	model->m_vertices[21].z = 92680;

	model->m_vertices[22].x = 76799;
	model->m_vertices[22].y = 74007;
	model->m_vertices[22].z = 462;

	model->m_vertices[23].x = -76679;
	model->m_vertices[23].y = 74240;
	model->m_vertices[23].z = -341;

	model->m_indices[0] = 0;
	model->m_indices[1] = 1;
	model->m_indices[2] = 2;
	model->m_indices[3] = 3;
	model->m_indices[4] = 4;
	model->m_indices[5] = 5;
	model->m_indices[6] = 6;
	model->m_indices[7] = 7;
	model->m_indices[8] = 8;
	model->m_indices[9] = 9;
	model->m_indices[10] = 10;
	model->m_indices[11] = 11;
	model->m_indices[12] = 12;
	model->m_indices[13] = 13;
	model->m_indices[14] = 14;
	model->m_indices[15] = 15;
	model->m_indices[16] = 16;
	model->m_indices[17] = 17;
	model->m_indices[18] = 18;
	model->m_indices[19] = 19;
	model->m_indices[20] = 20;
	model->m_indices[21] = 21;
	model->m_indices[22] = 22;
	model->m_indices[23] = 23;
	model->m_texCoords[0].u = 1024;
	model->m_texCoords[0].v = -62976;
	model->m_texCoords[1].u = 62976;
	model->m_texCoords[1].v = -63488;
	model->m_texCoords[2].u = 31232;
	model->m_texCoords[2].v = -31232;
	model->m_texCoords[3].u = 31232;
	model->m_texCoords[3].v = -31232;
	model->m_texCoords[4].u = 62976;
	model->m_texCoords[4].v = -63488;
	model->m_texCoords[5].u = 63488;
	model->m_texCoords[5].v = -1536;
	model->m_texCoords[6].u = 1024;
	model->m_texCoords[6].v = -62976;
	model->m_texCoords[7].u = 33280;
	model->m_texCoords[7].v = -33280;
	model->m_texCoords[8].u = 62976;
	model->m_texCoords[8].v = -63488;
	model->m_texCoords[9].u = 63488;
	model->m_texCoords[9].v = -1536;
	model->m_texCoords[10].u = 1536;
	model->m_texCoords[10].v = -1024;
	model->m_texCoords[11].u = 31232;
	model->m_texCoords[11].v = -31232;
	model->m_texCoords[12].u = 33280;
	model->m_texCoords[12].v = -33280;
	model->m_texCoords[13].u = 1536;
	model->m_texCoords[13].v = -1024;
	model->m_texCoords[14].u = 63488;
	model->m_texCoords[14].v = -1536;
	model->m_texCoords[15].u = 1024;
	model->m_texCoords[15].v = -62976;
	model->m_texCoords[16].u = 1536;
	model->m_texCoords[16].v = -1024;
	model->m_texCoords[17].u = 33280;
	model->m_texCoords[17].v = -33280;
	model->m_texCoords[18].u = 63488;
	model->m_texCoords[18].v = -1536;
	model->m_texCoords[19].u = 62976;
	model->m_texCoords[19].v = -63488;
	model->m_texCoords[20].u = 33280;
	model->m_texCoords[20].v = -33280;
	model->m_texCoords[21].u = 1024;
	model->m_texCoords[21].v = -62976;
	model->m_texCoords[22].u = 31232;
	model->m_texCoords[22].v = -31232;
	model->m_texCoords[23].u = 1536;
	model->m_texCoords[23].v = -1024;
	return model;
}
#endif