#ifndef _island3_
#define _island3_

#include "RenderData.h"

//This file was auto generated by Model Converter v0.5

RenderData* Getisland3()
{ 
	RenderData* model = new RenderData();
	model->m_numVertices = 126;
	model->m_numIndices = 126;
	model->m_numColorData = 0;
	model->m_numTexCoords = 126;

	model->m_vertices = new Vector3[model->m_numVertices];
	model->m_indices = new uint16[model->m_numIndices];
	model->m_texCoords = new TexCoord2[model->m_numTexCoords];

	model->m_vertices[0].x = 33523;
	model->m_vertices[0].y = -31726;
	model->m_vertices[0].z = 90756;

	model->m_vertices[1].x = -71294;
	model->m_vertices[1].y = -73122;
	model->m_vertices[1].z = -2792;

	model->m_vertices[2].x = 70491;
	model->m_vertices[2].y = -73122;
	model->m_vertices[2].z = -2792;

	model->m_vertices[3].x = 120490;
	model->m_vertices[3].y = 120719;
	model->m_vertices[3].z = -2792;

	model->m_vertices[4].x = 52633;
	model->m_vertices[4].y = 57551;
	model->m_vertices[4].z = 94993;

	model->m_vertices[5].x = 70491;
	model->m_vertices[5].y = -73122;
	model->m_vertices[5].z = -2792;

	model->m_vertices[6].x = -71294;
	model->m_vertices[6].y = -73122;
	model->m_vertices[6].z = -2792;

	model->m_vertices[7].x = -71294;
	model->m_vertices[7].y = 68663;
	model->m_vertices[7].z = -2792;

	model->m_vertices[8].x = 70491;
	model->m_vertices[8].y = -73122;
	model->m_vertices[8].z = -2792;

	model->m_vertices[9].x = 60813;
	model->m_vertices[9].y = 80847;
	model->m_vertices[9].z = 378820;

	model->m_vertices[10].x = -50802;
	model->m_vertices[10].y = 30169;
	model->m_vertices[10].z = 378820;

	model->m_vertices[11].x = 106060;
	model->m_vertices[11].y = -34266;
	model->m_vertices[11].z = 378820;

	model->m_vertices[12].x = -29987;
	model->m_vertices[12].y = 31784;
	model->m_vertices[12].z = 90756;

	model->m_vertices[13].x = 52633;
	model->m_vertices[13].y = 57551;
	model->m_vertices[13].z = 94993;

	model->m_vertices[14].x = -71294;
	model->m_vertices[14].y = 68663;
	model->m_vertices[14].z = -2792;

	model->m_vertices[15].x = -29987;
	model->m_vertices[15].y = 31784;
	model->m_vertices[15].z = 90756;

	model->m_vertices[16].x = -71294;
	model->m_vertices[16].y = 68663;
	model->m_vertices[16].z = -2792;

	model->m_vertices[17].x = -29987;
	model->m_vertices[17].y = -31726;
	model->m_vertices[17].z = 90756;

	model->m_vertices[18].x = 37527;
	model->m_vertices[18].y = -22411;
	model->m_vertices[18].z = 205889;

	model->m_vertices[19].x = -33767;
	model->m_vertices[19].y = -68198;
	model->m_vertices[19].z = 189627;

	model->m_vertices[20].x = 33523;
	model->m_vertices[20].y = -31726;
	model->m_vertices[20].z = 90756;

	model->m_vertices[21].x = -55054;
	model->m_vertices[21].y = 16226;
	model->m_vertices[21].z = 212922;

	model->m_vertices[22].x = -1302;
	model->m_vertices[22].y = 65527;
	model->m_vertices[22].z = 219748;

	model->m_vertices[23].x = -29987;
	model->m_vertices[23].y = 31784;
	model->m_vertices[23].z = 90756;

	model->m_vertices[24].x = -33767;
	model->m_vertices[24].y = -68198;
	model->m_vertices[24].z = 189627;

	model->m_vertices[25].x = -55054;
	model->m_vertices[25].y = 16226;
	model->m_vertices[25].z = 212922;

	model->m_vertices[26].x = -29987;
	model->m_vertices[26].y = -31726;
	model->m_vertices[26].z = 90756;

	model->m_vertices[27].x = 141644;
	model->m_vertices[27].y = -63317;
	model->m_vertices[27].z = 281344;

	model->m_vertices[28].x = -59104;
	model->m_vertices[28].y = -154465;
	model->m_vertices[28].z = 281344;

	model->m_vertices[29].x = 37527;
	model->m_vertices[29].y = -22411;
	model->m_vertices[29].z = 205889;

	model->m_vertices[30].x = 37527;
	model->m_vertices[30].y = -22411;
	model->m_vertices[30].z = 205889;

	model->m_vertices[31].x = -1302;
	model->m_vertices[31].y = 65527;
	model->m_vertices[31].z = 219748;

	model->m_vertices[32].x = 152225;
	model->m_vertices[32].y = 60354;
	model->m_vertices[32].z = 303987;

	model->m_vertices[33].x = -55054;
	model->m_vertices[33].y = 16226;
	model->m_vertices[33].z = 212922;

	model->m_vertices[34].x = -140483;
	model->m_vertices[34].y = 52574;
	model->m_vertices[34].z = 281344;

	model->m_vertices[35].x = -1302;
	model->m_vertices[35].y = 65527;
	model->m_vertices[35].z = 219748;

	model->m_vertices[36].x = -148434;
	model->m_vertices[36].y = -70064;
	model->m_vertices[36].z = 303987;

	model->m_vertices[37].x = -50802;
	model->m_vertices[37].y = 30169;
	model->m_vertices[37].z = 378820;

	model->m_vertices[38].x = -140483;
	model->m_vertices[38].y = 52574;
	model->m_vertices[38].z = 281344;

	model->m_vertices[39].x = 152225;
	model->m_vertices[39].y = 60354;
	model->m_vertices[39].z = 303987;

	model->m_vertices[40].x = 106060;
	model->m_vertices[40].y = -34266;
	model->m_vertices[40].z = 378820;

	model->m_vertices[41].x = 141644;
	model->m_vertices[41].y = -63317;
	model->m_vertices[41].z = 281344;

	model->m_vertices[42].x = 60265;
	model->m_vertices[42].y = 143722;
	model->m_vertices[42].z = 326630;

	model->m_vertices[43].x = 60813;
	model->m_vertices[43].y = 80847;
	model->m_vertices[43].z = 378820;

	model->m_vertices[44].x = 152225;
	model->m_vertices[44].y = 60354;
	model->m_vertices[44].z = 303987;

	model->m_vertices[45].x = -59104;
	model->m_vertices[45].y = -154465;
	model->m_vertices[45].z = 326630;

	model->m_vertices[46].x = -5555;
	model->m_vertices[46].y = -84945;
	model->m_vertices[46].z = 378820;

	model->m_vertices[47].x = -148434;
	model->m_vertices[47].y = -70064;
	model->m_vertices[47].z = 303987;

	model->m_vertices[48].x = -59104;
	model->m_vertices[48].y = -154465;
	model->m_vertices[48].z = 281344;

	model->m_vertices[49].x = -59104;
	model->m_vertices[49].y = -154465;
	model->m_vertices[49].z = 326630;

	model->m_vertices[50].x = -148434;
	model->m_vertices[50].y = -70064;
	model->m_vertices[50].z = 303987;

	model->m_vertices[51].x = -148434;
	model->m_vertices[51].y = -70064;
	model->m_vertices[51].z = 303987;

	model->m_vertices[52].x = -140483;
	model->m_vertices[52].y = 52574;
	model->m_vertices[52].z = 281344;

	model->m_vertices[53].x = -33767;
	model->m_vertices[53].y = -68198;
	model->m_vertices[53].z = 189627;

	model->m_vertices[54].x = -59104;
	model->m_vertices[54].y = -154465;
	model->m_vertices[54].z = 281344;

	model->m_vertices[55].x = -148434;
	model->m_vertices[55].y = -70064;
	model->m_vertices[55].z = 303987;

	model->m_vertices[56].x = -33767;
	model->m_vertices[56].y = -68198;
	model->m_vertices[56].z = 189627;

	model->m_vertices[57].x = -50802;
	model->m_vertices[57].y = 30169;
	model->m_vertices[57].z = 378820;

	model->m_vertices[58].x = -148434;
	model->m_vertices[58].y = -70064;
	model->m_vertices[58].z = 303987;

	model->m_vertices[59].x = -5555;
	model->m_vertices[59].y = -84945;
	model->m_vertices[59].z = 378820;

	model->m_vertices[60].x = -55054;
	model->m_vertices[60].y = 16226;
	model->m_vertices[60].z = 212922;

	model->m_vertices[61].x = -33767;
	model->m_vertices[61].y = -68198;
	model->m_vertices[61].z = 189627;

	model->m_vertices[62].x = -140483;
	model->m_vertices[62].y = 52574;
	model->m_vertices[62].z = 281344;

	model->m_vertices[63].x = 141644;
	model->m_vertices[63].y = -63317;
	model->m_vertices[63].z = 281344;

	model->m_vertices[64].x = 37527;
	model->m_vertices[64].y = -22411;
	model->m_vertices[64].z = 205889;

	model->m_vertices[65].x = 152225;
	model->m_vertices[65].y = 60354;
	model->m_vertices[65].z = 303987;

	model->m_vertices[66].x = -140483;
	model->m_vertices[66].y = 52574;
	model->m_vertices[66].z = 281344;

	model->m_vertices[67].x = 60265;
	model->m_vertices[67].y = 143722;
	model->m_vertices[67].z = 326630;

	model->m_vertices[68].x = -1302;
	model->m_vertices[68].y = 65527;
	model->m_vertices[68].z = 219748;

	model->m_vertices[69].x = 106060;
	model->m_vertices[69].y = -34266;
	model->m_vertices[69].z = 378820;

	model->m_vertices[70].x = 152225;
	model->m_vertices[70].y = 60354;
	model->m_vertices[70].z = 303987;

	model->m_vertices[71].x = 60813;
	model->m_vertices[71].y = 80847;
	model->m_vertices[71].z = 378820;

	model->m_vertices[72].x = 60813;
	model->m_vertices[72].y = 80847;
	model->m_vertices[72].z = 378820;

	model->m_vertices[73].x = 60265;
	model->m_vertices[73].y = 143722;
	model->m_vertices[73].z = 326630;

	model->m_vertices[74].x = -50802;
	model->m_vertices[74].y = 30169;
	model->m_vertices[74].z = 378820;

	model->m_vertices[75].x = 60265;
	model->m_vertices[75].y = 143722;
	model->m_vertices[75].z = 326630;

	model->m_vertices[76].x = -140483;
	model->m_vertices[76].y = 52574;
	model->m_vertices[76].z = 281344;

	model->m_vertices[77].x = -50802;
	model->m_vertices[77].y = 30169;
	model->m_vertices[77].z = 378820;

	model->m_vertices[78].x = 33523;
	model->m_vertices[78].y = -31726;
	model->m_vertices[78].z = 90756;

	model->m_vertices[79].x = 52633;
	model->m_vertices[79].y = 57551;
	model->m_vertices[79].z = 94993;

	model->m_vertices[80].x = 37527;
	model->m_vertices[80].y = -22411;
	model->m_vertices[80].z = 205889;

	model->m_vertices[81].x = -29987;
	model->m_vertices[81].y = -31726;
	model->m_vertices[81].z = 90756;

	model->m_vertices[82].x = -71294;
	model->m_vertices[82].y = -73122;
	model->m_vertices[82].z = -2792;

	model->m_vertices[83].x = 33523;
	model->m_vertices[83].y = -31726;
	model->m_vertices[83].z = 90756;

	model->m_vertices[84].x = 33523;
	model->m_vertices[84].y = -31726;
	model->m_vertices[84].z = 90756;

	model->m_vertices[85].x = 70491;
	model->m_vertices[85].y = -73122;
	model->m_vertices[85].z = -2792;

	model->m_vertices[86].x = 52633;
	model->m_vertices[86].y = 57551;
	model->m_vertices[86].z = 94993;

	model->m_vertices[87].x = 120490;
	model->m_vertices[87].y = 120719;
	model->m_vertices[87].z = -2792;

	model->m_vertices[88].x = 70491;
	model->m_vertices[88].y = -73122;
	model->m_vertices[88].z = -2792;

	model->m_vertices[89].x = -71294;
	model->m_vertices[89].y = 68663;
	model->m_vertices[89].z = -2792;

	model->m_vertices[90].x = -5555;
	model->m_vertices[90].y = -84945;
	model->m_vertices[90].z = 378820;

	model->m_vertices[91].x = 106060;
	model->m_vertices[91].y = -34266;
	model->m_vertices[91].z = 378820;

	model->m_vertices[92].x = -50802;
	model->m_vertices[92].y = 30169;
	model->m_vertices[92].z = 378820;

	model->m_vertices[93].x = 120490;
	model->m_vertices[93].y = 120719;
	model->m_vertices[93].z = -2792;

	model->m_vertices[94].x = -71294;
	model->m_vertices[94].y = 68663;
	model->m_vertices[94].z = -2792;

	model->m_vertices[95].x = 52633;
	model->m_vertices[95].y = 57551;
	model->m_vertices[95].z = 94993;

	model->m_vertices[96].x = -71294;
	model->m_vertices[96].y = -73122;
	model->m_vertices[96].z = -2792;

	model->m_vertices[97].x = -29987;
	model->m_vertices[97].y = -31726;
	model->m_vertices[97].z = 90756;

	model->m_vertices[98].x = -71294;
	model->m_vertices[98].y = 68663;
	model->m_vertices[98].z = -2792;

	model->m_vertices[99].x = -29987;
	model->m_vertices[99].y = -31726;
	model->m_vertices[99].z = 90756;

	model->m_vertices[100].x = 33523;
	model->m_vertices[100].y = -31726;
	model->m_vertices[100].z = 90756;

	model->m_vertices[101].x = -33767;
	model->m_vertices[101].y = -68198;
	model->m_vertices[101].z = 189627;

	model->m_vertices[102].x = 52633;
	model->m_vertices[102].y = 57551;
	model->m_vertices[102].z = 94993;

	model->m_vertices[103].x = -29987;
	model->m_vertices[103].y = 31784;
	model->m_vertices[103].z = 90756;

	model->m_vertices[104].x = -1302;
	model->m_vertices[104].y = 65527;
	model->m_vertices[104].z = 219748;

	model->m_vertices[105].x = -29987;
	model->m_vertices[105].y = 31784;
	model->m_vertices[105].z = 90756;

	model->m_vertices[106].x = -29987;
	model->m_vertices[106].y = -31726;
	model->m_vertices[106].z = 90756;

	model->m_vertices[107].x = -55054;
	model->m_vertices[107].y = 16226;
	model->m_vertices[107].z = 212922;

	model->m_vertices[108].x = -33767;
	model->m_vertices[108].y = -68198;
	model->m_vertices[108].z = 189627;

	model->m_vertices[109].x = 37527;
	model->m_vertices[109].y = -22411;
	model->m_vertices[109].z = 205889;

	model->m_vertices[110].x = -59104;
	model->m_vertices[110].y = -154465;
	model->m_vertices[110].z = 281344;

	model->m_vertices[111].x = -59104;
	model->m_vertices[111].y = -154465;
	model->m_vertices[111].z = 281344;

	model->m_vertices[112].x = 141644;
	model->m_vertices[112].y = -63317;
	model->m_vertices[112].z = 281344;

	model->m_vertices[113].x = -59104;
	model->m_vertices[113].y = -154465;
	model->m_vertices[113].z = 326630;

	model->m_vertices[114].x = -1302;
	model->m_vertices[114].y = 65527;
	model->m_vertices[114].z = 219748;

	model->m_vertices[115].x = 37527;
	model->m_vertices[115].y = -22411;
	model->m_vertices[115].z = 205889;

	model->m_vertices[116].x = 52633;
	model->m_vertices[116].y = 57551;
	model->m_vertices[116].z = 94993;

	model->m_vertices[117].x = 152225;
	model->m_vertices[117].y = 60354;
	model->m_vertices[117].z = 303987;

	model->m_vertices[118].x = -1302;
	model->m_vertices[118].y = 65527;
	model->m_vertices[118].z = 219748;

	model->m_vertices[119].x = 60265;
	model->m_vertices[119].y = 143722;
	model->m_vertices[119].z = 326630;

	model->m_vertices[120].x = 106060;
	model->m_vertices[120].y = -34266;
	model->m_vertices[120].z = 378820;

	model->m_vertices[121].x = -5555;
	model->m_vertices[121].y = -84945;
	model->m_vertices[121].z = 378820;

	model->m_vertices[122].x = 141644;
	model->m_vertices[122].y = -63317;
	model->m_vertices[122].z = 281344;

	model->m_vertices[123].x = -59104;
	model->m_vertices[123].y = -154465;
	model->m_vertices[123].z = 326630;

	model->m_vertices[124].x = 141644;
	model->m_vertices[124].y = -63317;
	model->m_vertices[124].z = 281344;

	model->m_vertices[125].x = -5555;
	model->m_vertices[125].y = -84945;
	model->m_vertices[125].z = 378820;

	model->m_indices[0] = 0;
	model->m_indices[1] = 1;
	model->m_indices[2] = 2;
	model->m_indices[3] = 3;
	model->m_indices[4] = 4;
	model->m_indices[5] = 5;
	model->m_indices[6] = 6;
	model->m_indices[7] = 7;
	model->m_indices[8] = 8;
	model->m_indices[9] = 9;
	model->m_indices[10] = 10;
	model->m_indices[11] = 11;
	model->m_indices[12] = 12;
	model->m_indices[13] = 13;
	model->m_indices[14] = 14;
	model->m_indices[15] = 15;
	model->m_indices[16] = 16;
	model->m_indices[17] = 17;
	model->m_indices[18] = 18;
	model->m_indices[19] = 19;
	model->m_indices[20] = 20;
	model->m_indices[21] = 21;
	model->m_indices[22] = 22;
	model->m_indices[23] = 23;
	model->m_indices[24] = 24;
	model->m_indices[25] = 25;
	model->m_indices[26] = 26;
	model->m_indices[27] = 27;
	model->m_indices[28] = 28;
	model->m_indices[29] = 29;
	model->m_indices[30] = 30;
	model->m_indices[31] = 31;
	model->m_indices[32] = 32;
	model->m_indices[33] = 33;
	model->m_indices[34] = 34;
	model->m_indices[35] = 35;
	model->m_indices[36] = 36;
	model->m_indices[37] = 37;
	model->m_indices[38] = 38;
	model->m_indices[39] = 39;
	model->m_indices[40] = 40;
	model->m_indices[41] = 41;
	model->m_indices[42] = 42;
	model->m_indices[43] = 43;
	model->m_indices[44] = 44;
	model->m_indices[45] = 45;
	model->m_indices[46] = 46;
	model->m_indices[47] = 47;
	model->m_indices[48] = 48;
	model->m_indices[49] = 49;
	model->m_indices[50] = 50;
	model->m_indices[51] = 51;
	model->m_indices[52] = 52;
	model->m_indices[53] = 53;
	model->m_indices[54] = 54;
	model->m_indices[55] = 55;
	model->m_indices[56] = 56;
	model->m_indices[57] = 57;
	model->m_indices[58] = 58;
	model->m_indices[59] = 59;
	model->m_indices[60] = 60;
	model->m_indices[61] = 61;
	model->m_indices[62] = 62;
	model->m_indices[63] = 63;
	model->m_indices[64] = 64;
	model->m_indices[65] = 65;
	model->m_indices[66] = 66;
	model->m_indices[67] = 67;
	model->m_indices[68] = 68;
	model->m_indices[69] = 69;
	model->m_indices[70] = 70;
	model->m_indices[71] = 71;
	model->m_indices[72] = 72;
	model->m_indices[73] = 73;
	model->m_indices[74] = 74;
	model->m_indices[75] = 75;
	model->m_indices[76] = 76;
	model->m_indices[77] = 77;
	model->m_indices[78] = 78;
	model->m_indices[79] = 79;
	model->m_indices[80] = 80;
	model->m_indices[81] = 81;
	model->m_indices[82] = 82;
	model->m_indices[83] = 83;
	model->m_indices[84] = 84;
	model->m_indices[85] = 85;
	model->m_indices[86] = 86;
	model->m_indices[87] = 87;
	model->m_indices[88] = 88;
	model->m_indices[89] = 89;
	model->m_indices[90] = 90;
	model->m_indices[91] = 91;
	model->m_indices[92] = 92;
	model->m_indices[93] = 93;
	model->m_indices[94] = 94;
	model->m_indices[95] = 95;
	model->m_indices[96] = 96;
	model->m_indices[97] = 97;
	model->m_indices[98] = 98;
	model->m_indices[99] = 99;
	model->m_indices[100] = 100;
	model->m_indices[101] = 101;
	model->m_indices[102] = 102;
	model->m_indices[103] = 103;
	model->m_indices[104] = 104;
	model->m_indices[105] = 105;
	model->m_indices[106] = 106;
	model->m_indices[107] = 107;
	model->m_indices[108] = 108;
	model->m_indices[109] = 109;
	model->m_indices[110] = 110;
	model->m_indices[111] = 111;
	model->m_indices[112] = 112;
	model->m_indices[113] = 113;
	model->m_indices[114] = 114;
	model->m_indices[115] = 115;
	model->m_indices[116] = 116;
	model->m_indices[117] = 117;
	model->m_indices[118] = 118;
	model->m_indices[119] = 119;
	model->m_indices[120] = 120;
	model->m_indices[121] = 121;
	model->m_indices[122] = 122;
	model->m_indices[123] = 123;
	model->m_indices[124] = 124;
	model->m_indices[125] = 125;
	model->m_texCoords[0].u = 26070;
	model->m_texCoords[0].v = -17777;
	model->m_texCoords[1].u = 49305;
	model->m_texCoords[1].v = -3599;
	model->m_texCoords[2].u = 17548;
	model->m_texCoords[2].v = -3022;
	model->m_texCoords[3].u = 9332;
	model->m_texCoords[3].v = 0;
	model->m_texCoords[4].u = 23145;
	model->m_texCoords[4].v = -17090;
	model->m_texCoords[5].u = 17548;
	model->m_texCoords[5].v = -3022;
	model->m_texCoords[6].u = 49305;
	model->m_texCoords[6].v = -3599;
	model->m_texCoords[7].u = 51486;
	model->m_texCoords[7].v = -1536;
	model->m_texCoords[8].u = 17548;
	model->m_texCoords[8].v = -3022;
	model->m_texCoords[9].u = 20473;
	model->m_texCoords[9].v = -62854;
	model->m_texCoords[10].u = 44693;
	model->m_texCoords[10].v = -64045;
	model->m_texCoords[11].u = 8567;
	model->m_texCoords[11].v = -64345;
	model->m_texCoords[12].u = 41272;
	model->m_texCoords[12].v = -17111;
	model->m_texCoords[13].u = 23145;
	model->m_texCoords[13].v = -17090;
	model->m_texCoords[14].u = 51486;
	model->m_texCoords[14].v = -1536;
	model->m_texCoords[15].u = 41272;
	model->m_texCoords[15].v = -17111;
	model->m_texCoords[16].u = 51486;
	model->m_texCoords[16].v = -1536;
	model->m_texCoords[17].u = 40295;
	model->m_texCoords[17].v = -18035;
	model->m_texCoords[18].u = 24830;
	model->m_texCoords[18].v = -36340;
	model->m_texCoords[19].u = 40163;
	model->m_texCoords[19].v = -34653;
	model->m_texCoords[20].u = 26070;
	model->m_texCoords[20].v = -17777;
	model->m_texCoords[21].u = 46131;
	model->m_texCoords[21].v = -37298;
	model->m_texCoords[22].u = 34822;
	model->m_texCoords[22].v = -37472;
	model->m_texCoords[23].u = 41272;
	model->m_texCoords[23].v = -17111;
	model->m_texCoords[24].u = 40163;
	model->m_texCoords[24].v = -34653;
	model->m_texCoords[25].u = 46131;
	model->m_texCoords[25].v = -37298;
	model->m_texCoords[26].u = 40295;
	model->m_texCoords[26].v = -18035;
	model->m_texCoords[27].u = 562;
	model->m_texCoords[27].v = -48778;
	model->m_texCoords[28].u = 44123;
	model->m_texCoords[28].v = -50920;
	model->m_texCoords[29].u = 24830;
	model->m_texCoords[29].v = -36340;
	model->m_texCoords[30].u = 24830;
	model->m_texCoords[30].v = -36340;
	model->m_texCoords[31].u = 34822;
	model->m_texCoords[31].v = -37472;
	model->m_texCoords[32].u = 0;
	model->m_texCoords[32].v = -50616;
	model->m_texCoords[33].u = 46131;
	model->m_texCoords[33].v = -37298;
	model->m_texCoords[34].u = 65536;
	model->m_texCoords[34].v = -48239;
	model->m_texCoords[35].u = 34822;
	model->m_texCoords[35].v = -37472;
	model->m_texCoords[36].u = 65334;
	model->m_texCoords[36].v = -53736;
	model->m_texCoords[37].u = 44693;
	model->m_texCoords[37].v = -64045;
	model->m_texCoords[38].u = 65536;
	model->m_texCoords[38].v = -48239;
	model->m_texCoords[39].u = 0;
	model->m_texCoords[39].v = -50616;
	model->m_texCoords[40].u = 8567;
	model->m_texCoords[40].v = -64345;
	model->m_texCoords[41].u = 562;
	model->m_texCoords[41].v = -48778;
	model->m_texCoords[42].u = 21783;
	model->m_texCoords[42].v = -53458;
	model->m_texCoords[43].u = 20473;
	model->m_texCoords[43].v = -62854;
	model->m_texCoords[44].u = 0;
	model->m_texCoords[44].v = -50616;
	model->m_texCoords[45].u = 43932;
	model->m_texCoords[45].v = -58281;
	model->m_texCoords[46].u = 32787;
	model->m_texCoords[46].v = -65536;
	model->m_texCoords[47].u = 65334;
	model->m_texCoords[47].v = -53736;
	model->m_texCoords[48].u = 44123;
	model->m_texCoords[48].v = -50920;
	model->m_texCoords[49].u = 43932;
	model->m_texCoords[49].v = -58281;
	model->m_texCoords[50].u = 65334;
	model->m_texCoords[50].v = -53736;
	model->m_texCoords[51].u = 65334;
	model->m_texCoords[51].v = -53736;
	model->m_texCoords[52].u = 65536;
	model->m_texCoords[52].v = -48239;
	model->m_texCoords[53].u = 40163;
	model->m_texCoords[53].v = -34653;
	model->m_texCoords[54].u = 44123;
	model->m_texCoords[54].v = -50920;
	model->m_texCoords[55].u = 65334;
	model->m_texCoords[55].v = -53736;
	model->m_texCoords[56].u = 40163;
	model->m_texCoords[56].v = -34653;
	model->m_texCoords[57].u = 44693;
	model->m_texCoords[57].v = -64045;
	model->m_texCoords[58].u = 65334;
	model->m_texCoords[58].v = -53736;
	model->m_texCoords[59].u = 32787;
	model->m_texCoords[59].v = -65536;
	model->m_texCoords[60].u = 46131;
	model->m_texCoords[60].v = -37298;
	model->m_texCoords[61].u = 40163;
	model->m_texCoords[61].v = -34653;
	model->m_texCoords[62].u = 65536;
	model->m_texCoords[62].v = -48239;
	model->m_texCoords[63].u = 562;
	model->m_texCoords[63].v = -48778;
	model->m_texCoords[64].u = 24830;
	model->m_texCoords[64].v = -36340;
	model->m_texCoords[65].u = 0;
	model->m_texCoords[65].v = -50616;
	model->m_texCoords[66].u = 65536;
	model->m_texCoords[66].v = -48239;
	model->m_texCoords[67].u = 21783;
	model->m_texCoords[67].v = -53458;
	model->m_texCoords[68].u = 34822;
	model->m_texCoords[68].v = -37472;
	model->m_texCoords[69].u = 8567;
	model->m_texCoords[69].v = -64345;
	model->m_texCoords[70].u = 0;
	model->m_texCoords[70].v = -50616;
	model->m_texCoords[71].u = 20473;
	model->m_texCoords[71].v = -62854;
	model->m_texCoords[72].u = 20473;
	model->m_texCoords[72].v = -62854;
	model->m_texCoords[73].u = 21783;
	model->m_texCoords[73].v = -53458;
	model->m_texCoords[74].u = 44693;
	model->m_texCoords[74].v = -64045;
	model->m_texCoords[75].u = 21783;
	model->m_texCoords[75].v = -53458;
	model->m_texCoords[76].u = 65536;
	model->m_texCoords[76].v = -48239;
	model->m_texCoords[77].u = 44693;
	model->m_texCoords[77].v = -64045;
	model->m_texCoords[78].u = 26070;
	model->m_texCoords[78].v = -17777;
	model->m_texCoords[79].u = 23145;
	model->m_texCoords[79].v = -17090;
	model->m_texCoords[80].u = 24830;
	model->m_texCoords[80].v = -36340;
	model->m_texCoords[81].u = 40295;
	model->m_texCoords[81].v = -18035;
	model->m_texCoords[82].u = 49305;
	model->m_texCoords[82].v = -3599;
	model->m_texCoords[83].u = 26070;
	model->m_texCoords[83].v = -17777;
	model->m_texCoords[84].u = 26070;
	model->m_texCoords[84].v = -17777;
	model->m_texCoords[85].u = 17548;
	model->m_texCoords[85].v = -3022;
	model->m_texCoords[86].u = 23145;
	model->m_texCoords[86].v = -17090;
	model->m_texCoords[87].u = 9332;
	model->m_texCoords[87].v = 0;
	model->m_texCoords[88].u = 17548;
	model->m_texCoords[88].v = -3022;
	model->m_texCoords[89].u = 51486;
	model->m_texCoords[89].v = -1536;
	model->m_texCoords[90].u = 32787;
	model->m_texCoords[90].v = -65536;
	model->m_texCoords[91].u = 8567;
	model->m_texCoords[91].v = -64345;
	model->m_texCoords[92].u = 44693;
	model->m_texCoords[92].v = -64045;
	model->m_texCoords[93].u = 9332;
	model->m_texCoords[93].v = 0;
	model->m_texCoords[94].u = 51486;
	model->m_texCoords[94].v = -1536;
	model->m_texCoords[95].u = 23145;
	model->m_texCoords[95].v = -17090;
	model->m_texCoords[96].u = 49305;
	model->m_texCoords[96].v = -3599;
	model->m_texCoords[97].u = 40295;
	model->m_texCoords[97].v = -18035;
	model->m_texCoords[98].u = 51486;
	model->m_texCoords[98].v = -1536;
	model->m_texCoords[99].u = 40295;
	model->m_texCoords[99].v = -18035;
	model->m_texCoords[100].u = 26070;
	model->m_texCoords[100].v = -17777;
	model->m_texCoords[101].u = 40163;
	model->m_texCoords[101].v = -34653;
	model->m_texCoords[102].u = 23145;
	model->m_texCoords[102].v = -17090;
	model->m_texCoords[103].u = 41272;
	model->m_texCoords[103].v = -17111;
	model->m_texCoords[104].u = 34822;
	model->m_texCoords[104].v = -37472;
	model->m_texCoords[105].u = 41272;
	model->m_texCoords[105].v = -17111;
	model->m_texCoords[106].u = 40295;
	model->m_texCoords[106].v = -18035;
	model->m_texCoords[107].u = 46131;
	model->m_texCoords[107].v = -37298;
	model->m_texCoords[108].u = 40163;
	model->m_texCoords[108].v = -34653;
	model->m_texCoords[109].u = 24830;
	model->m_texCoords[109].v = -36340;
	model->m_texCoords[110].u = 44123;
	model->m_texCoords[110].v = -50920;
	model->m_texCoords[111].u = 44123;
	model->m_texCoords[111].v = -50920;
	model->m_texCoords[112].u = 562;
	model->m_texCoords[112].v = -48778;
	model->m_texCoords[113].u = 43932;
	model->m_texCoords[113].v = -58281;
	model->m_texCoords[114].u = 34822;
	model->m_texCoords[114].v = -37472;
	model->m_texCoords[115].u = 24830;
	model->m_texCoords[115].v = -36340;
	model->m_texCoords[116].u = 23145;
	model->m_texCoords[116].v = -17090;
	model->m_texCoords[117].u = 0;
	model->m_texCoords[117].v = -50616;
	model->m_texCoords[118].u = 34822;
	model->m_texCoords[118].v = -37472;
	model->m_texCoords[119].u = 21783;
	model->m_texCoords[119].v = -53458;
	model->m_texCoords[120].u = 8567;
	model->m_texCoords[120].v = -64345;
	model->m_texCoords[121].u = 32787;
	model->m_texCoords[121].v = -65536;
	model->m_texCoords[122].u = 562;
	model->m_texCoords[122].v = -48778;
	model->m_texCoords[123].u = 43932;
	model->m_texCoords[123].v = -58281;
	model->m_texCoords[124].u = 562;
	model->m_texCoords[124].v = -48778;
	model->m_texCoords[125].u = 32787;
	model->m_texCoords[125].v = -65536;
	return model;
}
#endif